
	    function NO_MP_INDEX(stat)
            return stat
        end

        function ADD_MP_INDEX(stat)
            local Exceptions = {
                "MP_CHAR_STAT_RALLY_ANIM",
                "MP_CHAR_ARMOUR_1_COUNT",
                "MP_CHAR_ARMOUR_2_COUNT",
                "MP_CHAR_ARMOUR_3_COUNT",
                "MP_CHAR_ARMOUR_4_COUNT",
                "MP_CHAR_ARMOUR_5_COUNT",
            }
            for _, exception in pairs(Exceptions) do
                if stat == exception then
                    return "MP" .. util.get_char_slot() .. "_" .. stat
                end
            end

            if not string.contains(stat, "MP_") and not string.contains(stat, "MPPLY_") then
                return "MP" .. util.get_char_slot() .. "_" .. stat
            end
            return stat
        end

        function STAT_SET_INT(stat, value)
            STATS.STAT_SET_INT(util.joaat(NO_MP_INDEX(stat)), value, true)
        end
		
		function STAT_SET_FLOAT(stat, value)
            STATS.STAT_SET_FLOAT(util.joaat(NO_MP_INDEX(stat)), value, true)
        end
		
		
        function STAT_SET_BOOL(stat, value)
            STATS.STAT_SET_BOOL(util.joaat(NO_MP_INDEX(stat)), value, true)
        end
        function STAT_SET_STRING(stat, value)
            STATS.STAT_SET_STRING(util.joaat(NO_MP_INDEX(stat)), value, true)
        end

        function STAT_SET_MASKED_INT(stat, value1, value2)
            STATS.STAT_SET_MASKED_INT(util.joaat(NO_MP_INDEX(stat)), value1, value2, 8, true)
        end
		
		
			function STAT_SET_MASKED_BOOL(statName, value, mask)
			native_invoker.begin_call();
			
			native_invoker.push_arg_int(statName);
			native_invoker.push_arg_bool(value);
			native_invoker.push_arg_int(mask);
			native_invoker.push_arg_bool(true);
			--native_invoker.end_call_2(0x5BC62EC1937B9E5B)
			--STATS.STAT_SET_BOOL_MASKED(util.joaat(NO_MP_INDEX(stat)), value1, value2, true)
			--STATS.STAT_SET_MASKED_BOOL(util.joaat(NO_MP_INDEX(stat)), value1, value2, true)
			
	    end
		
		
		
		
        function SET_PACKED_STAT_BOOL_CODE(stat, value)
            STATS.SET_PACKED_STAT_BOOL_CODE(stat, value, util.get_char_slot())
        end
        function STAT_INCREMENT(stat, value)
            STATS.STAT_INCREMENT(util.joaat(NO_MP_INDEX(stat)), value, true)
        end

        function STAT_GET_INT(stat)
            local IntPTR = memory.alloc_int()
            STATS.STAT_GET_INT(util.joaat(NO_MP_INDEX(stat)), IntPTR, -1)
            return memory.read_int(IntPTR)
        end
        function STAT_GET_STRING(stat)
            return STATS.STAT_GET_STRING(util.joaat(NO_MP_INDEX(stat)), -1)
        end

        function SET_INT_GLOBAL(global, value)
            memory.write_int(memory.script_global(global), value)
        end
        function SET_INT_TUNABLE_GLOBAL(hash, value)
            memory.write_int(memory.script_global(262145 + memory.tunable_offset(hash)), value)
        end
        function SET_FLOAT_GLOBAL(global, value)
            memory.write_float(memory.script_global(global), value)
        end
        function SET_FLOAT_TUNABLE_GLOBAL(hash, value)
            memory.write_float(memory.script_global(262145 + memory.tunable_offset(hash)), value)
        end

        function GET_INT_GLOBAL(global)
            return memory.read_int(memory.script_global(global))
        end

        function SET_PACKED_INT_GLOBAL(start_global, end_global, value)
            for i = start_global, end_global do
                SET_INT_GLOBAL(262145 + i, value)
            end
        end
        function SET_PACKED_INT_TUNABLE_GLOBAL(start_hash, end_hash, value)
            for i = memory.tunable_offset(start_hash), memory.tunable_offset(end_hash) do
                SET_INT_GLOBAL(262145 + i, value)
            end
        end

        function SET_INT_LOCAL(script, script_local, value)
            if memory.script_local(script, script_local) ~= 0 then
                memory.write_int(memory.script_local(script, script_local), value)
            end
        end
        function SET_FLOAT_LOCAL(script, script_local, value)
            if memory.script_local(script, script_local) ~= 0 then
                memory.write_float(memory.script_local(script, script_local), value)
            end
        end

        function GET_INT_LOCAL(script, script_local)
            if memory.script_local(script, script_local) ~= 0 then
                local ReadLocal = memory.read_int(memory.script_local(script, script_local))
                if ReadLocal ~= nil then
                    return ReadLocal
                end
            end
        end

        function SET_BIT(bits, place) -- Credit goes to WiriScript
            return (bits | (1 << place))
        end
        function SET_LOCAL_BIT(script, script_local, bit)
            if memory.script_local(script, script_local) ~= 0 then
                local Addr = memory.script_local(script, script_local)
                memory.write_int(Addr, SET_BIT(memory.read_int(Addr), bit))
            end
        end

    ---



        util.require_natives(1681379138)
        util.keep_running()



 function rn()
 	math.random(); math.random()
	math.random(); math.random()
	local rnndd = math.random(1,60)
	math.random(); math.random()
	math.random(); math.random()
	return rnndd

 end
 
local function mpx()
	local mpp = util.get_char_slot()
	if mpp ~= nil then
		return "MP"..mpp.."_"
	end 
	return  "MPX_"
end

function UnlockALLparachutes()
	STAT_SET_MASKED_BOOL(mpx() .. "TUNERPSTAT_BOOL1", true, 20)  --  Unlock for Sprunk Chute Bag
	STAT_SET_MASKED_BOOL(mpx() .. "TUNERPSTAT_BOOL1", true, 21)  --  Unlock for eCola Chute Bag
	STAT_SET_MASKED_BOOL(mpx() .. "TUNERPSTAT_BOOL1", true, 22)  --  Unlock for Halloween Chute Bag
	STAT_SET_MASKED_BOOL(mpx() .. "TUNERPSTAT_BOOL1", true, 23)  --  Unlock for Sprunk Chute
	STAT_SET_MASKED_BOOL(mpx() .. "TUNERPSTAT_BOOL1", true, 24)  --  Unlock for eCola Chute
	STAT_SET_MASKED_BOOL(mpx() .. "TUNERPSTAT_BOOL1", true, 25)  --  Unlock for Halloween Chute
	STAT_SET_MASKED_BOOL(mpx() .. "DLC12022PSTAT_BOOL1", true, 63)  --  Unlock Junk Energy Drink Chute Bag
	STAT_SET_MASKED_BOOL(mpx() .. "DLC12022PSTAT_BOOL2", true, 0)  --  Unlock Junk Energy Drink Chute
	STAT_SET_MASKED_BOOL(mpx() .. "TUPSTAT_BOOL7", true, 50)  --  Unlock High Flyer Chute Bag
end


function CompleteDailyObjectives()
    local function setStats(prefix, value)
        STAT_SET_INT(mpx() .. prefix, value)
    end
    
    local function setBoolStats(prefix, value)
        STAT_SET_BOOL(mpx() .. prefix, value)
    end
    STAT_SET_INT("COMPLETEDAILYOBJ", 100)
    STAT_SET_INT("COMPLETEDAILYOBJTOTAL", 100)
    STAT_SET_INT("TOTALDAYCOMPLETED", 100)
    STAT_SET_INT("TOTALWEEKCOMPLETED", 400)
    STAT_SET_INT("TOTALMONTHCOMPLETED", 1800)
    STAT_SET_INT("CONSECUTIVEDAYCOMPLETED", 30)
    STAT_SET_INT("CONSECUTIVEWEEKCOMPLETED", 4)
    STAT_SET_INT("CONSECUTIVEMONTHCOMPLETE", 1)

    STAT_SET_INT("COMPLETEDAILYOBJSA", 100)
    STAT_SET_INT("COMPLETEDAILYOBJTOTALSA", 100)
    STAT_SET_INT("TOTALDAYCOMPLETEDSA", 100)
    STAT_SET_INT("TOTALWEEKCOMPLETEDSA", 400)
    STAT_SET_INT("TOTALMONTHCOMPLETEDSA", 1800)
    STAT_SET_INT("CONSECUTIVEDAYCOMPLETEDSA", 30)
    STAT_SET_INT("CONSECUTIVEWEEKCOMPLETEDSA", 4)
    STAT_SET_INT("CONSECUTIVEMONTHCOMPLETESA", 1)

    STAT_SET_INT("AWD_DAILYOBJCOMPLETEDSA", 100)
    STAT_SET_INT("AWD_DAILYOBJCOMPLETED", 100)

    setBoolStats("AWD_DAILYOBJMONTHBONUS", true)
    setBoolStats("AWD_DAILYOBJWEEKBONUS", true)
    setBoolStats("AWD_DAILYOBJWEEKBONUSSA", true)
    setBoolStats("AWD_DAILYOBJMONTHBONUSSA", true)
end

local function setBadsport()
	STAT_SET_INT("MPPLY_BADSPORT_MESSAGE", 0)
	STAT_SET_INT("MPPLY_BECAME_BADSPORT_NUM", 0)
    STAT_SET_FLOAT("MPPLY_OVERALL_BADSPORT", 0)
    STAT_SET_BOOL("MPPLY_CHAR_IS_BADSPORT", false)
end

local function UnlockEngineUpgrades()
    local upgradeValue = 50
    STAT_SET_INT(mpx() .. "USJS_COMPLETED_MASK", upgradeValue)
    STAT_SET_INT(mpx().. "USJS_FOUND_MASK", upgradeValue)
    STAT_SET_INT(mpx() .. "USJS_TOTAL_COMPLETED", upgradeValue)
    STAT_SET_INT(mpx() .. "USJS_COMPLETED", upgradeValue)
    STAT_SET_INT(mpx() .. "USJS_FOUND", upgradeValue)
end

function unlockFastRunReload()
  local abilities = {"CHAR_ABILITY_1_UNLCK", "CHAR_ABILITY_2_UNLCK", "CHAR_ABILITY_3_UNLCK", 
                     "CHAR_FM_ABILITY_1_UNLCK", "CHAR_FM_ABILITY_2_UNLCK", "CHAR_FM_ABILITY_3_UNLCK"}

  local scripts = {"SCRIPT_INCREASE_DRIV", "SCRIPT_INCREASE_FLY", "SCRIPT_INCREASE_LUNG", 
                   "SCRIPT_INCREASE_SHO", "SCRIPT_INCREASE_STAM", "SCRIPT_INCREASE_STL", 
                   "SCRIPT_INCREASE_STRN", "SCRIPT_INCREASE_MECH"}

  for _, ability in ipairs(abilities) do
    STAT_SET_INT(ability, -1)
  end
  for _, script in ipairs(scripts) do
    STAT_SET_INT(script, 100)
  end
end
function SpecialTats()
	for i = 0, 63 do
		for z = 0, 05 do
			STAT_SET_MASKED_BOOL(mpx() .. "_GUNTATPSTAT_BOOL" .. z, true, i, mpxx)
		end
	end
end
function UnlockALL()
		SpecialTats()
		unlockFastRunReload()
		setBadsport()
		UnlockEngineUpgrades()
		CompleteDailyObjectives()
		STAT_SET_INT('MPX_AWD_BATSWORD', 1000000)
		STAT_SET_INT('MPX_AWD_COINPURSE', 950000)
		STAT_SET_INT('MPX_AWD_ASTROCHIMP', 3000000)
		STAT_SET_INT('MPX_AWD_MASTERFUL', 40000)
		STAT_SET_INT('MPX_SCGW_NUM_WINS_GANG_0', 55)
		STAT_SET_INT('MPX_SCGW_NUM_WINS_GANG_1', 56)
		STAT_SET_INT('MPX_SCGW_NUM_WINS_GANG_2', 57)
		STAT_SET_INT('MPX_SCGW_NUM_WINS_GANG_3', 58)
		STAT_SET_INT('MPX_IAP_MAX_MOON_DIST', 2147483647)
		STAT_SET_INT('MPX_LAST_ANIMAL', 108)
		STAT_SET_INT('MPX_CH_ARC_CAB_CLAW_TROPHY', -1)
		STAT_SET_INT('MPX_CH_ARC_CAB_LOVE_TROPHY', -1)
		STAT_SET_INT('MPX_AWD_FACES_OF_DEATH', 50)
		STAT_SET_INT('MPX_REV_NV_KILLS', 50)
		STAT_SET_INT("MPX_XM22_FLOW", -1)
		STAT_SET_INT("MPX_XM22_MISSIONS", -1)
		STAT_SET_BOOL("MPX_AWD_DOGS_BEST_FRIEND", true)
		STAT_SET_INT("MPX_H3_VEHICLESUSED", -1)
		STAT_SET_INT("MPX_H4_H4_DJ_MISSIONS", -1)
		STAT_SET_INT("MPX_H4_PROGRESS", -1)
		STAT_SET_INT("MPX_TUNER_GEN_BS", -1)
		STAT_SET_INT("MPX_FIXER_HQ_OWNED", 1)
		STAT_SET_INT("MPX_ULP_MISSION_PROGRESS", -1)
		STAT_SET_INT("MPX_SUM23_AVOP_PROGRESS", -1)
		STAT_SET_INT("MPX_GANGOPS_FLOW_BITSET_MISS0", -1)
		STAT_SET_BOOL("MPX_AWD_TAXISTAR", true)
		STAT_SET_BOOL("MPPLY_AWD_HST_ORDER", true)
		STAT_SET_BOOL("MPPLY_AWD_HST_SAME_TEAM", true)
		STAT_SET_BOOL("MPPLY_AWD_HST_ULT_CHAL", true)
		STAT_SET_INT("MPPLY_HEISTFLOWORDERPROGRESS", -1)
		STAT_SET_INT("MPPLY_HEISTNODEATHPROGREITSET", -1)
		STAT_SET_INT("MPPLY_HEISTTEAMPROGRESSBITSET", -1)
		STAT_SET_INT("MPX_AT_FLOW_VEHICLE_BS", -1)
		STAT_SET_INT("MPX_LFETIME_HANGAR_BUY_COMPLET", 50)
		STAT_SET_INT("MPX_SALV23_GEN_BS", -1)
		STAT_SET_INT("MPX_SALV23_INST_PROG", -1)
		STAT_SET_INT("MPX_SALV23_SCOPE_BS", -1)
		STAT_SET_INT("MPX_MOST_TIME_ON_3_PLUS_STARS", 300000)
        STAT_SET_INT("MPX_LOWRIDER_FLOW_COMPLETE", 1)
        STAT_SET_INT("MPX_AT_FLOW_MISSION_PROGRESS", 50)
        STAT_SET_INT("MPX_AT_FLOW_IMPEXP_NUM", 50)
        STAT_SET_INT("MPX_AT_FLOW_BITSET_MISSIONS0", -1)
        STAT_SET_INT("MPX_WVM_FLOW_MISSION_PROGRESS", 50)
        STAT_SET_INT("MPX_WVM_FLOW_IMPEXP_NUM", 50)
        STAT_SET_INT("MPX_WVM_FLOW_BITSET_MISSIONS0", -1)
        STAT_SET_INT("MPX_WVM_FLOW_VEHICLE_BS", -1)
        STAT_SET_INT("MPX_GANGOPS_FLOW_MISSION_PROG", -1)
        STAT_SET_INT("MPX_GANGOPS_FLOW_IMPEXP_NUM", 50)
        STAT_SET_INT("MPX_WAM_FLOW_VEHICLE_BS", -1)
        STAT_SET_INT("MPX_GANGOPS_FLOW_PASSED_BITSET", -1)
        STAT_SET_INT("MPX_VCM_FLOW_PROGRESS", -1)
        STAT_SET_INT("MPX_TUNER_FLOW_BS", -1)
        STAT_SET_INT("MPX_TUNER_MIS_BS", -1)
        STAT_SET_INT("MPX_TUNER_COMP_BS", -1)
        STAT_SET_INT("MPX_GANGOPS_FM_MISSION_PROG", -1)
        STAT_SET_INT("MPX_GANGOPS_FM_BITSET_MISS0", -1)
        STAT_SET_BOOL("MPX_UNLOCKED_MESSAGE_FLEECA", true)
        STAT_SET_BOOL("MPX_CARMEET_PV_CHLLGE_CMPLT", true)
        STAT_SET_INT("MPX_LIFETIME_BUY_COMPLETE", 1025 + rn())
        STAT_SET_INT("MPX_LIFETIME_BUY_UNDERTAKEN", 1025 + rn())
        STAT_SET_INT("MPX_LIFETIME_SELL_COMPLETE", 1025 + rn())
        STAT_SET_INT("MPX_LIFETIME_SELL_UNDERTAKEN", 1025 + rn())
        STAT_SET_INT("MPX_LIFETIME_CONTRA_EARNINGS", 25000000) --Contraband Earnings
        STAT_SET_INT("MPX_LFETIME_BIKER_BUY_COMPLET", 1025 + rn())
        STAT_SET_INT("MPX_LFETIME_BIKER_BUY_UNDERTA", 1025 + rn())
        STAT_SET_INT("MPX_LFETIME_BIKER_SELL_COMPLET", 1025 + rn())
        STAT_SET_INT("MPX_LFETIME_BIKER_SELL_UNDERTA", 1025 + rn())
        STAT_SET_INT("MPX_LFETIME_BIKER_BUY_COMPLET1", 1025 + rn())
        STAT_SET_INT("MPX_LFETIME_BIKER_BUY_UNDERTA1", 1025 + rn())
        STAT_SET_INT("MPX_LFETIME_BIKER_SELL_COMPLET1", 1025 + rn())
        STAT_SET_INT("MPX_LFETIME_BIKER_SELL_UNDERTA1", 1025 + rn())
        STAT_SET_INT("MPX_LFETIME_BIKER_BUY_COMPLET2", 1025 + rn())
        STAT_SET_INT("MPX_LFETIME_BIKER_BUY_UNDERTA2", 1025 + rn())
        STAT_SET_INT("MPX_LFETIME_BIKER_SELL_COMPLET2", 1025 + rn())
        STAT_SET_INT("MPX_LFETIME_BIKER_SELL_UNDERTA2", 1025 + rn())
        STAT_SET_INT("MPX_LFETIME_BIKER_BUY_COMPLET3", 1025 + rn())
        STAT_SET_INT("MPX_LFETIME_BIKER_BUY_UNDERTA3", 1025 + rn())
        STAT_SET_INT("MPX_LFETIME_BIKER_SELL_COMPLET3", 1025 + rn())
        STAT_SET_INT("MPX_LFETIME_BIKER_SELL_UNDERTA3", 1025 + rn())
        STAT_SET_INT("MPX_LFETIME_BIKER_BUY_COMPLET4", 1025 + rn())
        STAT_SET_INT("MPX_LFETIME_BIKER_BUY_UNDERTA4", 1025 + rn())
        STAT_SET_INT("MPX_LFETIME_BIKER_SELL_COMPLET4", 1025 + rn())
        STAT_SET_INT("MPX_LFETIME_BIKER_SELL_UNDERTA4", 1025 + rn())
        STAT_SET_INT("MPX_LFETIME_BIKER_BUY_COMPLET5", 1025 + rn())
        STAT_SET_INT("MPX_LFETIME_BIKER_BUY_UNDERTA5", 1025 + rn())
        STAT_SET_INT("MPX_LFETIME_BIKER_SELL_COMPLET5", 1025 + rn())
        STAT_SET_INT("MPX_LFETIME_BIKER_SELL_UNDERTA5", 1025 + rn())
        STAT_SET_INT("MPX_LIFETIME_BKR_SELL_EARNINGS0", 25000000)
        STAT_SET_INT("MPX_LIFETIME_BKR_SELL_EARNINGS1", 25000000)
        STAT_SET_INT("MPX_LIFETIME_BKR_SELL_EARNINGS2", 25000000)
        STAT_SET_INT("MPX_LIFETIME_BKR_SELL_EARNINGS3", 25000000)
        STAT_SET_INT("MPX_LIFETIME_BKR_SELL_EARNINGS4", 25000000)
        STAT_SET_INT("MPX_LFETIME_BIKER_BUY_COMPLET6", 10) 
        STAT_SET_INT("MPX_LFETIME_BIKER_SELL_COMPLET6", 10) 
        STAT_SET_INT('MPPLY_CREW_NO_HEISTS_0', 2)
        STAT_SET_INT('MPPLY_CREW_NO_HEISTS_1', 5)
        STAT_SET_INT('MPPLY_CREW_NO_HEISTS_2', 5)
        STAT_SET_INT('MPPLY_CREW_NO_HEISTS_3', 5)
        STAT_SET_INT('MPPLY_CREW_NO_HEISTS_4', 5)
        STAT_SET_INT('MPPLY_GANGOPS_LOYALTY2', -1)
        STAT_SET_INT('MPPLY_GANGOPS_LOYALTY3', -1)
        STAT_SET_INT('MPPLY_GANGOPS_CRIMMASMD2', -1)
        STAT_SET_INT('MPPLY_GANGOPS_CRIMMASMD3', -1)
        STAT_SET_INT('MPPLY_GANGOPS_SUPPORT', -1)
        STAT_SET_INT('MPPLY_GANGOPS_ALLINORDER', -1)
        STAT_SET_INT('MPPLY_GANGOPS_LOYALTY', -1)
        STAT_SET_INT('MPPLY_GANGOPS_CRIMMASMD', -1)
        STAT_SET_INT('MPPLY_XMASLIVERIES0', -1)
        STAT_SET_INT('MPPLY_XMASLIVERIES1', -1)
        STAT_SET_INT('MPPLY_XMASLIVERIES2', -1)
        STAT_SET_INT('MPPLY_XMASLIVERIES3', -1)
        STAT_SET_INT('MPPLY_XMASLIVERIES4', -1)
        STAT_SET_INT('MPPLY_XMASLIVERIES5', -1)
        STAT_SET_INT('MPPLY_XMASLIVERIES6', -1)
        STAT_SET_INT('MPPLY_XMASLIVERIES7', -1)
        STAT_SET_INT('MPPLY_XMASLIVERIES8', -1)
        STAT_SET_INT('MPPLY_XMASLIVERIES9', -1)
        STAT_SET_INT('MPPLY_XMASLIVERIES10', -1)
        STAT_SET_INT('MPPLY_XMASLIVERIES11', -1)
        STAT_SET_INT('MPPLY_XMASLIVERIES12', -1)
        STAT_SET_INT('MPPLY_XMASLIVERIES13', -1)
        STAT_SET_INT('MPPLY_XMASLIVERIES14', -1)
        STAT_SET_INT('MPPLY_XMASLIVERIES15', -1)
        STAT_SET_INT('MPPLY_XMASLIVERIES16', -1)
        STAT_SET_INT('MPPLY_XMASLIVERIES17', -1)
        STAT_SET_INT('MPPLY_XMASLIVERIES18', -1)
        STAT_SET_INT('MPPLY_XMASLIVERIES19', -1)
        STAT_SET_INT('MPPLY_XMASLIVERIES20', -1)
        STAT_SET_INT('MPX_HOLDUPS_BITSET', -1)
        STAT_SET_INT('MPX_CHAR_ABILITY_1_UNLCK', -1)
        STAT_SET_INT('MPX_CHAR_ABILITY_2_UNLCK', -1)
        STAT_SET_INT('MPX_CHAR_ABILITY_3_UNLCK', -1)
        STAT_SET_INT('MPX_CHAR_WEAP_UNLOCKED', -1)
        STAT_SET_INT('MPX_CHAR_WEAP_UNLOCKED2', -1)
        STAT_SET_INT('MPX_CHAR_WEAP_ADDON_1_UNLCK', -1)
        STAT_SET_INT('MPX_CHAR_WEAP_ADDON_2_UNLCK', -1)
        STAT_SET_INT('MPX_CHAR_WEAP_ADDON_3_UNLCK', -1)
        STAT_SET_INT('MPX_CHAR_WEAP_ADDON_4_UNLCK', -1)
        STAT_SET_INT('MPX_CHAR_FM_WEAP_UNLOCKED', -1)
        STAT_SET_INT('MPX_CHAR_FM_WEAP_UNLOCKED2', -1)
        STAT_SET_INT('MPX_CHAR_FM_WEAP_UNLOCKED3', -1)
        STAT_SET_INT('MPX_CHAR_FM_WEAP_UNLOCKED4', -1)
        STAT_SET_INT('MPX_CHAR_FM_WEAP_UNLOCKED5', -1)
        STAT_SET_INT('MPX_CHAR_FM_WEAP_ADDON_1_UNLCK', -1)
        STAT_SET_INT('MPX_CHAR_FM_WEAP_ADDON_2_UNLCK', -1)
        STAT_SET_INT('MPX_CHAR_FM_WEAP_ADDON_3_UNLCK', -1)
        STAT_SET_INT('MPX_CHAR_FM_WEAP_ADDON_4_UNLCK', -1)
        STAT_SET_INT('MPX_CHAR_FM_WEAP_ADDON_5_UNLCK', -1)
        STAT_SET_INT('MPX_CHAR_FM_WEAP_ADDON_6_UNLCK', -1)
        STAT_SET_INT('MPX_CHAR_FM_WEAP_ADDON_7_UNLCK', -1)
        STAT_SET_INT('MPX_CHAR_FM_WEAP_ADDON_8_UNLCK', -1)
        STAT_SET_INT('MPX_CHAR_FM_WEAP_ADDON_9_UNLCK', -1)
        STAT_SET_INT('MPX_CHAR_FM_WEAP_ADDON_10_UNLCK', -1)
        STAT_SET_INT('MPX_CHAR_FM_WEAP_ADDON_11_UNLCK', -1)
        STAT_SET_INT('MPX_CHAR_FM_WEAP_ADDON_12_UNLCK', -1)
        STAT_SET_INT('MPX_CHAR_FM_WEAP_ADDON_13_UNLCK', -1)
        STAT_SET_INT('MPX_CHAR_FM_WEAP_ADDON_14_UNLCK', -1)
        STAT_SET_INT('MPX_CHAR_FM_WEAP_ADDON_15_UNLCK', -1)
        STAT_SET_INT('MPX_CHAR_FM_WEAP_ADDON_16_UNLCK', -1)
        STAT_SET_INT('MPX_CHAR_FM_WEAP_ADDON_17_UNLCK', -1)
        STAT_SET_INT('MPX_CHAR_FM_WEAP_ADDON_18_UNLCK', -1)
        STAT_SET_INT('MPX_CHAR_FM_WEAP_ADDON_19_UNLCK', -1)
        STAT_SET_INT('MPX_CHAR_FM_WEAP_ADDON_20_UNLCK', -1)
        STAT_SET_INT('MPX_CHAR_FM_HAIRCUT_1_UNLCK', -1)
        STAT_SET_INT('MPX_CHAR_HAIR_UNLCK1', -1)
        STAT_SET_INT('MPX_CHAR_HAIR_UNLCK2', -1)
        STAT_SET_INT('MPX_CHAR_HAIR_UNLCK3', -1)
        STAT_SET_INT('MPX_CHAR_HAIR_UNLCK4', -1)
        STAT_SET_INT('MPX_CHAR_HAIR_UNLCK5', -1)
        STAT_SET_INT('MPX_CHAR_HAIR_UNLCK6', -1)
        STAT_SET_INT('MPX_CHAR_HAIR_UNLCK7', -1)
        STAT_SET_INT('MPX_CHAR_HAIR_UNLCK8', -1)
        STAT_SET_INT('MPX_CHAR_HAIR_UNLCK9', -1)
        STAT_SET_INT('MPX_CHAR_HAIR_UNLCK10', -1)
        STAT_SET_INT('MPX_CHAR_HAIR_UNLCK11', -1)
        STAT_SET_INT('MPX_CHAR_HAIR_UNLCK12', -1)
        STAT_SET_INT('MPX_CHAR_HAIR_UNLCK13', -1)
        STAT_SET_INT('MPX_CHAR_HAIR_UNLCK14', -1)
        STAT_SET_INT('MPX_CHAR_HAIR_UNLCK15', -1)
        STAT_SET_INT('MPX_CHAR_HAIR_UNLCK16', -1)
        STAT_SET_INT('MPX_CHAR_HAIR_UNLCK17', -1)
        STAT_SET_INT('MPX_CHAR_FM_HEALTH_1_UNLCK', -1)
        STAT_SET_INT('MPX_CHAR_FM_HEALTH_2_UNLCK', -1)
        STAT_SET_INT('MPX_CRDEADLINE', 5)
        STAT_SET_INT('MPX_CHAR_CREWUNLOCK_1_FM_EQUIP', -1)
        STAT_SET_INT('MPX_CHAR_CREWUNLOCK_2_FM_EQUIP', -1)
        STAT_SET_INT('MPX_CHAR_CREWUNLOCK_3_FM_EQUIP', -1)
        STAT_SET_INT('MPX_CHAR_CREWUNLOCK_4_FM_EQUIP', -1)
        STAT_SET_INT('MPX_CHAR_CREWUNLOCK_5_FM_EQUIP', -1)
        STAT_SET_INT('MPX_CHAR_KIT_1_FM_UNLCK', -1)
        STAT_SET_INT('MPX_CHAR_KIT_2_FM_UNLCK', -1)
        STAT_SET_INT('MPX_CHAR_KIT_3_FM_UNLCK', -1)
        STAT_SET_INT('MPX_CHAR_KIT_4_FM_UNLCK', -1)
        STAT_SET_INT('MPX_CHAR_KIT_5_FM_UNLCK', -1)
        STAT_SET_INT('MPX_CHAR_KIT_6_FM_UNLCK', -1)
        STAT_SET_INT('MPX_CHAR_KIT_7_FM_UNLCK', -1)
        STAT_SET_INT('MPX_CHAR_KIT_8_FM_UNLCK', -1)
        STAT_SET_INT('MPX_CHAR_KIT_9_FM_UNLCK', -1)
        STAT_SET_INT('MPX_CHAR_KIT_10_FM_UNLCK', -1)
        STAT_SET_INT('MPX_CHAR_KIT_11_FM_UNLCK', -1)
        STAT_SET_INT('MPX_CHAR_KIT_12_FM_UNLCK', -1)
        STAT_SET_INT('MPX_CHAR_KIT_13_FM_UNLCK', -1)
        STAT_SET_INT('MPX_CHAR_KIT_14_FM_UNLCK', -1)
        STAT_SET_INT('MPX_CHAR_KIT_15_FM_UNLCK', -1)
        STAT_SET_INT('MPX_CHAR_KIT_16_FM_UNLCK', -1)
        STAT_SET_INT('MPX_CHAR_KIT_17_FM_UNLCK', -1)
        STAT_SET_INT('MPX_CHAR_KIT_18_FM_UNLCK', -1)
        STAT_SET_INT('MPX_CHAR_KIT_19_FM_UNLCK', -1)
        STAT_SET_INT('MPX_CHAR_KIT_20_FM_UNLCK', -1)
        STAT_SET_INT('MPX_CHAR_KIT_21_FM_UNLCK', -1)
        STAT_SET_INT('MPX_CHAR_KIT_22_FM_UNLCK', -1)
        STAT_SET_INT('MPX_CHAR_KIT_23_FM_UNLCK', -1)
        STAT_SET_INT('MPX_CHAR_KIT_24_FM_UNLCK', -1)
        STAT_SET_INT('MPX_CHAR_KIT_25_FM_UNLCK', -1)
        STAT_SET_INT('MPX_CHAR_KIT_26_FM_UNLCK', -1)
        STAT_SET_INT('MPX_CHAR_KIT_27_FM_UNLCK', -1)
        STAT_SET_INT('MPX_CHAR_KIT_28_FM_UNLCK', -1)
        STAT_SET_INT('MPX_CHAR_KIT_29_FM_UNLCK', -1)
        STAT_SET_INT('MPX_CHAR_KIT_30_FM_UNLCK', -1)
        STAT_SET_INT('MPX_CHAR_KIT_30_FM_UNLCK', -1)
        STAT_SET_INT('MPX_CHAR_KIT_31_FM_UNLCK', -1)
        STAT_SET_INT('MPX_CHAR_KIT_32_FM_UNLCK', -1)
        STAT_SET_INT('MPX_CHAR_KIT_33_FM_UNLCK', -1)
        STAT_SET_INT('MPX_CHAR_KIT_34_FM_UNLCK', -1)
        STAT_SET_INT('MPX_CHAR_KIT_35_FM_UNLCK', -1)
        STAT_SET_INT('MPX_CHAR_KIT_36_FM_UNLCK', -1)
        STAT_SET_INT('MPX_CHAR_KIT_37_FM_UNLCK', -1)
        STAT_SET_INT('MPX_CHAR_KIT_38_FM_UNLCK', -1)
        STAT_SET_INT('MPX_CHAR_KIT_39_FM_UNLCK', -1)
        STAT_SET_INT('MPX_CHAR_KIT_40_FM_UNLCK', -1)
        STAT_SET_INT('MPX_CHAR_KIT_41_FM_UNLCK', -1)
        STAT_SET_INT('MPX_CHAR_FM_ABILITY_1_UNLCK', -1)
        STAT_SET_INT('MPX_CHAR_FM_ABILITY_2_UNLCK', -1)
        STAT_SET_INT('MPX_CHAR_FM_ABILITY_3_UNLCK', -1)
        STAT_SET_INT('MPX_CHAR_FM_CLOTHES_1_UNLCK', -1)
        STAT_SET_INT('MPX_CHAR_FM_CLOTHES_2_UNLCK', -1)
        STAT_SET_INT('MPX_CHAR_FM_CLOTHES_3_UNLCK', -1)
        STAT_SET_INT('MPX_CHAR_FM_CLOTHES_4_UNLCK', -1)
        STAT_SET_INT('MPX_CHAR_FM_CLOTHES_5_UNLCK', -1)
        STAT_SET_INT('MPX_CHAR_FM_CLOTHES_6_UNLCK', -1)
        STAT_SET_INT('MPX_CHAR_FM_CLOTHES_7_UNLCK', -1)
        STAT_SET_INT('MPX_CHAR_FM_CLOTHES_8_UNLCK', -1)
        STAT_SET_INT('MPX_CHAR_FM_CLOTHES_9_UNLCK', -1)
        STAT_SET_INT('MPX_CHAR_FM_CLOTHES_10_UNLCK', -1)
        STAT_SET_INT('MPX_CHAR_FM_CLOTHES_11_UNLCK', -1)
        STAT_SET_INT('MPX_CHAR_FM_VEHICLE_1_UNLCK', -1)
        STAT_SET_INT('MPX_CHAR_FM_VEHICLE_2_UNLCK', -1)
        STAT_SET_INT('MPX_TATTOO_FM_UNLOCKS_0', -1)
        STAT_SET_INT('MPX_TATTOO_FM_UNLOCKS_1', -1)
        STAT_SET_INT('MPX_TATTOO_FM_UNLOCKS_2', -1)
        STAT_SET_INT('MPX_TATTOO_FM_UNLOCKS_3', -1)
        STAT_SET_INT('MPX_TATTOO_FM_UNLOCKS_4', -1)
        STAT_SET_INT('MPX_TATTOO_FM_UNLOCKS_5', -1)
        STAT_SET_INT('MPX_TATTOO_FM_UNLOCKS_6', -1)
        STAT_SET_INT('MPX_TATTOO_FM_UNLOCKS_7', -1)
        STAT_SET_INT('MPX_TATTOO_FM_UNLOCKS_8', -1)
        STAT_SET_INT('MPX_TATTOO_FM_UNLOCKS_9', -1)
        STAT_SET_INT('MPX_TATTOO_FM_UNLOCKS_10', -1)
        STAT_SET_INT('MPX_TATTOO_FM_UNLOCKS_11', -1)
        STAT_SET_INT('MPX_TATTOO_FM_UNLOCKS_12', -1)
        STAT_SET_INT('MPX_TATTOO_FM_UNLOCKS_13', -1)
        STAT_SET_INT('MPX_TATTOO_FM_UNLOCKS_14', -1)
        STAT_SET_INT('MPX_TATTOO_FM_UNLOCKS_15', -1)
        STAT_SET_INT('MPX_TATTOO_FM_UNLOCKS_16', -1)
        STAT_SET_INT('MPX_TATTOO_FM_UNLOCKS_17', -1)
        STAT_SET_INT('MPX_TATTOO_FM_UNLOCKS_18', -1)
        STAT_SET_INT('MPX_TATTOO_FM_UNLOCKS_19', -1)
        STAT_SET_INT('MPX_TATTOO_FM_UNLOCKS_20', -1)
        STAT_SET_INT('MPX_TATTOO_FM_UNLOCKS_21', -1)
        STAT_SET_INT('MPX_TATTOO_FM_UNLOCKS_22', -1)
        STAT_SET_INT('MPX_TATTOO_FM_UNLOCKS_23', -1)
        STAT_SET_INT('MPX_TATTOO_FM_UNLOCKS_24', -1)
        STAT_SET_INT('MPX_TATTOO_FM_UNLOCKS_25', -1)
        STAT_SET_INT('MPX_TATTOO_FM_UNLOCKS_26', -1)
        STAT_SET_INT('MPX_TATTOO_FM_UNLOCKS_27', -1)
        STAT_SET_INT('MPX_TATTOO_FM_UNLOCKS_28', -1)
        STAT_SET_INT('MPX_TATTOO_FM_UNLOCKS_29', -1)
        STAT_SET_INT('MPX_TATTOO_FM_UNLOCKS_30', -1)
        STAT_SET_INT('MPX_TATTOO_FM_UNLOCKS_31', -1)
        STAT_SET_INT('MPX_TATTOO_FM_UNLOCKS_32', -1)
        STAT_SET_INT('MPX_TATTOO_FM_UNLOCKS_33', -1)
        STAT_SET_INT('MPX_TATTOO_FM_UNLOCKS_34', -1)
        STAT_SET_INT('MPX_TATTOO_FM_UNLOCKS_35', -1)
        STAT_SET_INT('MPX_TATTOO_FM_UNLOCKS_36', -1)
        STAT_SET_INT('MPX_TATTOO_FM_UNLOCKS_37', -1)
        STAT_SET_INT('MPX_TATTOO_FM_UNLOCKS_38', -1)
        STAT_SET_INT('MPX_TATTOO_FM_UNLOCKS_39', -1)
        STAT_SET_INT('MPX_TATTOO_FM_UNLOCKS_40', -1)
        STAT_SET_INT('MPX_TATTOO_FM_UNLOCKS_41', -1)
        STAT_SET_INT('MPX_TATTOO_FM_UNLOCKS_42', -1)
        STAT_SET_INT('MPX_TATTOO_FM_UNLOCKS_43', -1)
        STAT_SET_INT('MPX_TATTOO_FM_UNLOCKS_44', -1)
        STAT_SET_INT('MPX_TATTOO_FM_UNLOCKS_45', -1)
        STAT_SET_INT('MPX_TATTOO_FM_UNLOCKS_46', -1)
        STAT_SET_INT('MPX_TATTOO_FM_UNLOCKS_47', -1)
        STAT_SET_INT('MPX_TATTOO_FM_UNLOCKS_48', -1)
        STAT_SET_INT('MPX_TATTOO_FM_UNLOCKS_49', -1)
        STAT_SET_INT('MPX_TATTOO_FM_UNLOCKS_50', -1)
        STAT_SET_INT('MPX_TATTOO_FM_UNLOCKS_51', -1)
        STAT_SET_INT('MPX_TATTOO_FM_UNLOCKS_52', -1)
        STAT_SET_INT('MPX_TATTOO_FM_UNLOCKS_53', -1)
        STAT_SET_INT('MPX_RANKAP_UNLK_0', -1)
        STAT_SET_INT('MPX_RANKAP_UNLK_1', -1)
        STAT_SET_INT('MPX_RANKAP_UNLK_2', -1)
        STAT_SET_INT('MPX_RANKAP_UNLK_3', -1)
        STAT_SET_INT('MPX_CHAR_CREWUNLOCK_1_UNLCK', -1)
        STAT_SET_INT('MPX_SR_WEAPON_BIT_SET', -1)
        STAT_SET_INT('MPX_CAR_CLUB_REP', 997430)
        STAT_SET_BOOL('MPX_SR_TIER_1_REWARD', true)
        STAT_SET_BOOL('MPX_SR_INCREASE_THROW_CAP', true)
        STAT_SET_BOOL('MPX_SR_TIER_3_REWARD', true)
        STAT_SET_BOOL('MPPLY_MELEECHLENGECOMPLETED', true)
        STAT_SET_BOOL('MPPLY_HEADSHOTCHLENGECOMPLETED', true)
        STAT_SET_INT('MPX_CHAR_HEIST_1_UNLCK', -1)
        STAT_SET_INT('MPX_CHAR_FM_VEHICLE_1_UNLCK', -1)
        STAT_SET_INT('MPX_CHAR_FM_VEHICLE_2_UNLCK', -1)
        STAT_SET_INT('MPX_CRHEIST', 50)
        STAT_SET_INT('MPX_CR_BANKHEIST1', 10)
        STAT_SET_INT('MPX_CR_COUNTHEIST1', 10)
        STAT_SET_INT('MPX_HEIST_COMPLETION', 26)
        STAT_SET_INT('MPX_HEIST_TOTAL_TIME', 86400000)
        STAT_SET_INT('MPX_HEISTS_ORGANISED', 50)
        STAT_SET_INT('MPX_RACES_WON', 50)
        STAT_SET_INT('MPX_CHAR_FM_PACKAGE_1_COLLECT', -1)
        STAT_SET_INT('MPX_CHAR_FM_PACKAGE_2_COLLECT', -1)
        STAT_SET_INT('MPX_CHAR_FM_PACKAGE_3_COLLECT', -1)
        STAT_SET_INT('MPX_CHAR_FM_PACKAGE_4_COLLECT', -1)
        STAT_SET_INT('MPX_CHAR_FM_PACKAGE_5_COLLECT', -1)
        STAT_SET_INT('MPX_CHAR_FM_PACKAGE_6_COLLECT', -1)
        STAT_SET_INT('MPX_CHAR_FM_PACKAGE_7_COLLECT', -1)
        STAT_SET_INT('MPX_CHAR_FM_PACKAGE_8_COLLECT', -1)
        STAT_SET_INT('MPX_CHAR_NO_FM_PACKAGES_COL', -1)
        STAT_SET_INT('MPX_CHAR_FM_CARMOD_1_UNLCK', -1)
        STAT_SET_INT('MPX_CHAR_FM_CARMOD_2_UNLCK', -1)
        STAT_SET_INT('MPX_CHAR_FM_CARMOD_3_UNLCK', -1)
        STAT_SET_INT('MPX_CHAR_FM_CARMOD_4_UNLCK', -1)
        STAT_SET_INT('MPX_CHAR_FM_CARMOD_5_UNLCK', -1)
        STAT_SET_INT('MPX_CHAR_FM_CARMOD_6_UNLCK', -1)
        STAT_SET_INT('MPX_CHAR_FM_CARMOD_7_UNLCK', -1)
        STAT_SET_INT('MPX_NUMBER_SLIPSTREAMS_IN_RACE', 110)
        STAT_SET_INT('MPX_NUMBER_TURBO_STARTS_IN_RACE', 90)
        STAT_SET_INT('MPX_USJS_FOUND', 50)
        STAT_SET_INT('MPX_USJS_COMPLETED', 50)
        STAT_SET_INT('MPX_MPPLY_TIMES_RACE_BEST_LAP', 101)
        STAT_SET_INT('MPX_AWD_FMRALLYWONDRIVE', 25)
        STAT_SET_INT('MPX_AWD_FMWINSEARACE', 25)
        STAT_SET_INT('MPX_AWD_FMWINAIRRACE', 25)
        STAT_SET_INT('MPX_AWD_FM_RACES_FASTEST_LAP', 101)
        STAT_SET_INT('MPX_SCRIPT_INCREASE_STAM', 100)
        STAT_SET_INT('MPX_SCRIPT_INCREASE_STRN', 100)
        STAT_SET_INT('MPX_SCRIPT_INCREASE_FLY', 100)
        STAT_SET_INT('MPX_SCRIPT_INCREASE_STL', 100)
        STAT_SET_INT('MPX_SCRIPT_INCREASE_LUNG', 100)
        STAT_SET_INT('MPX_SCRIPT_INCREASE_DRIV', 100)
        STAT_SET_INT('MPX_SCRIPT_INCREASE_SHO', 100)
        STAT_SET_INT('MPX_AWD_DANCE_TO_SOLOMUN', 360)
        STAT_SET_INT('NIGHTCLUB_HOTSPOT_TIME_MS', 3600000)
        STAT_SET_INT('MPX_CASINO_DECORATION_GIFT_1', -1);
        STAT_SET_BOOL('MPX_COMPLETE_H4_F_USING_VETIR', true);
        STAT_SET_BOOL('MPX_COMPLETE_H4_F_USING_LONGFIN', true);
        STAT_SET_BOOL('MPX_COMPLETE_H4_F_USING_ANNIH', true);
        STAT_SET_BOOL('MPX_COMPLETE_H4_F_USING_ALKONOS', true);
        STAT_SET_BOOL('MPX_COMPLETE_H4_F_USING_PATROLB', true);
        STAT_SET_BOOL('MPX_AWD_DEADEYE', true)
		STAT_SET_BOOL('MPX_AWD_PISTOLSATDAWN', true)
		STAT_SET_BOOL('MPX_AWD_TRAFFICAVOI', true)
		STAT_SET_BOOL('MPX_AWD_CANTCATCHBRA', true)
		STAT_SET_BOOL('MPX_AWD_WIZHARD', true)
		STAT_SET_BOOL('MPX_AWD_APEESCAPE', true)
		STAT_SET_BOOL('MPX_AWD_MONKEYKIND', true)
		STAT_SET_BOOL('MPX_AWD_AQUAAPE', true)
		STAT_SET_BOOL('MPX_AWD_KEEPFAITH', true)
		STAT_SET_BOOL('MPX_AWD_TRUELOVE', true)
		STAT_SET_BOOL('MPX_AWD_NEMESIS', true)
		STAT_SET_BOOL('MPX_AWD_FRIENDZONED', true)
		STAT_SET_BOOL('MPX_SCGW_WON_NO_DEATHS', true)
		STAT_SET_BOOL('MPX_IAP_CHALLENGE_0', true)
		STAT_SET_BOOL('MPX_IAP_CHALLENGE_1', true)
		STAT_SET_BOOL('MPX_IAP_CHALLENGE_2', true)
		STAT_SET_BOOL('MPX_IAP_CHALLENGE_3', true)
		STAT_SET_BOOL('MPX_IAP_CHALLENGE_4', true)
		STAT_SET_BOOL('MPX_AWD_KINGOFQUB3D', true)
		STAT_SET_BOOL('MPX_AWD_QUBISM', true)
		STAT_SET_BOOL('MPX_AWD_GODOFQUB3D', true)
		STAT_SET_BOOL('MPX_AWD_QUIBITS', true)
		STAT_SET_BOOL('MPX_AWD_ELEVENELEVEN', true)
		STAT_SET_BOOL('MPX_AWD_GOFOR11TH', true)
		STAT_SET_BOOL('MPX_AWD_STRAIGHT_TO_VIDEO', true)
		STAT_SET_BOOL('MPX_AWD_MONKEY_C_MONKEY_DO', true)
		STAT_SET_BOOL('MPX_AWD_TRAINED_TO_KILL', true)
		STAT_SET_BOOL('MPX_AWD_DIRECTOR', true)
		STAT_SET_INT('MPX_AWD_SHARPSHOOTER', 40)
		STAT_SET_INT('MPX_AWD_RACECHAMP', 40)
		
		
		
		--------------------
		
		
		STAT_SET_INT(mpx()..'AWD_BATSWORD', 1000000)
		STAT_SET_INT(mpx()..'AWD_COINPURSE', 950000)
		STAT_SET_INT(mpx()..'AWD_ASTROCHIMP', 3000000)
		STAT_SET_INT(mpx()..'AWD_MASTERFUL', 40000)
		STAT_SET_INT(mpx()..'SCGW_NUM_WINS_GANG_0', 55)
		STAT_SET_INT(mpx()..'SCGW_NUM_WINS_GANG_1', 56)
		STAT_SET_INT(mpx()..'SCGW_NUM_WINS_GANG_2', 57)
		STAT_SET_INT(mpx()..'SCGW_NUM_WINS_GANG_3', 58)
		STAT_SET_INT(mpx()..'IAP_MAX_MOON_DIST', 2147483647)
		STAT_SET_INT(mpx()..'LAST_ANIMAL', 108)
		STAT_SET_INT(mpx()..'CH_ARC_CAB_CLAW_TROPHY', -1)
		STAT_SET_INT(mpx()..'CH_ARC_CAB_LOVE_TROPHY', -1)
		STAT_SET_INT(mpx()..'AWD_FACES_OF_DEATH', 50)
		STAT_SET_INT(mpx()..'REV_NV_KILLS', 50)
		STAT_SET_INT(mpx().."XM22_FLOW", -1)
		STAT_SET_INT(mpx().."XM22_MISSIONS", -1)
		STAT_SET_BOOL(mpx().."AWD_DOGS_BEST_FRIEND", true)
		STAT_SET_INT(mpx().."H3_VEHICLESUSED", -1)
		STAT_SET_INT(mpx().."H4_H4_DJ_MISSIONS", -1)
		STAT_SET_INT(mpx().."H4_PROGRESS", -1)
		STAT_SET_INT(mpx().."TUNER_GEN_BS", -1)
		STAT_SET_INT(mpx().."FIXER_HQ_OWNED", 1)
		STAT_SET_INT(mpx().."ULP_MISSION_PROGRESS", -1)
		STAT_SET_INT(mpx().."SUM23_AVOP_PROGRESS", -1)
		STAT_SET_INT(mpx().."GANGOPS_FLOW_BITSET_MISS0", -1)
		STAT_SET_BOOL(mpx().."AWD_TAXISTAR", true)
		STAT_SET_BOOL("MPPLY_AWD_HST_ORDER", true)
		STAT_SET_BOOL("MPPLY_AWD_HST_SAME_TEAM", true)
		STAT_SET_BOOL("MPPLY_AWD_HST_ULT_CHAL", true)
		STAT_SET_INT("MPPLY_HEISTFLOWORDERPROGRESS", -1)
		STAT_SET_INT("MPPLY_HEISTNODEATHPROGREITSET", -1)
		STAT_SET_INT("MPPLY_HEISTTEAMPROGRESSBITSET", -1)
		STAT_SET_INT(mpx().."AT_FLOW_VEHICLE_BS", -1)
		STAT_SET_INT(mpx().."LFETIME_HANGAR_BUY_COMPLET", 50)
		STAT_SET_INT(mpx().."SALV23_GEN_BS", -1)
		STAT_SET_INT(mpx().."SALV23_INST_PROG", -1)
		STAT_SET_INT(mpx().."SALV23_SCOPE_BS", -1)
		STAT_SET_INT(mpx().."MOST_TIME_ON_3_PLUS_STARS", 300000)
        STAT_SET_INT(mpx().."LOWRIDER_FLOW_COMPLETE", 1)
        STAT_SET_INT(mpx().."AT_FLOW_MISSION_PROGRESS", 50)
        STAT_SET_INT(mpx().."AT_FLOW_IMPEXP_NUM", 50)
        STAT_SET_INT(mpx().."AT_FLOW_BITSET_MISSIONS0", -1)
        STAT_SET_INT(mpx().."WVM_FLOW_MISSION_PROGRESS", 50)
        STAT_SET_INT(mpx().."WVM_FLOW_IMPEXP_NUM", 50)
        STAT_SET_INT(mpx().."WVM_FLOW_BITSET_MISSIONS0", -1)
        STAT_SET_INT(mpx().."WVM_FLOW_VEHICLE_BS", -1)
        STAT_SET_INT(mpx().."GANGOPS_FLOW_MISSION_PROG", -1)
        STAT_SET_INT(mpx().."GANGOPS_FLOW_IMPEXP_NUM", 50)
        STAT_SET_INT(mpx().."WAM_FLOW_VEHICLE_BS", -1)
        STAT_SET_INT(mpx().."GANGOPS_FLOW_PASSED_BITSET", -1)
        STAT_SET_INT(mpx().."VCM_FLOW_PROGRESS", -1)
        STAT_SET_INT(mpx().."TUNER_FLOW_BS", -1)
        STAT_SET_INT(mpx().."TUNER_MIS_BS", -1)
        STAT_SET_INT(mpx().."TUNER_COMP_BS", -1)
        STAT_SET_INT(mpx().."GANGOPS_FM_MISSION_PROG", -1)
        STAT_SET_INT(mpx().."GANGOPS_FM_BITSET_MISS0", -1)
        STAT_SET_BOOL(mpx().."UNLOCKED_MESSAGE_FLEECA", true)
        STAT_SET_BOOL(mpx().."CARMEET_PV_CHLLGE_CMPLT", true)
        STAT_SET_INT(mpx().."LIFETIME_BUY_COMPLETE", 1025 + rn())
        STAT_SET_INT(mpx().."LIFETIME_BUY_UNDERTAKEN", 1025 + rn())
        STAT_SET_INT(mpx().."LIFETIME_SELL_COMPLETE", 1025 + rn())
        STAT_SET_INT(mpx().."LIFETIME_SELL_UNDERTAKEN", 1025 + rn())
        STAT_SET_INT(mpx().."LIFETIME_CONTRA_EARNINGS", 25000000) --Contraband Earnings
        STAT_SET_INT(mpx().."LFETIME_BIKER_BUY_COMPLET", 1025 + rn())
        STAT_SET_INT(mpx().."LFETIME_BIKER_BUY_UNDERTA", 1025 + rn())
        STAT_SET_INT(mpx().."LFETIME_BIKER_SELL_COMPLET", 1025 + rn())
        STAT_SET_INT(mpx().."LFETIME_BIKER_SELL_UNDERTA", 1025 + rn())
        STAT_SET_INT(mpx().."LFETIME_BIKER_BUY_COMPLET1", 1025 + rn())
        STAT_SET_INT(mpx().."LFETIME_BIKER_BUY_UNDERTA1", 1025 + rn())
        STAT_SET_INT(mpx().."LFETIME_BIKER_SELL_COMPLET1", 1025 + rn())
        STAT_SET_INT(mpx().."LFETIME_BIKER_SELL_UNDERTA1", 1025 + rn())
        STAT_SET_INT(mpx().."LFETIME_BIKER_BUY_COMPLET2", 1025 + rn())
        STAT_SET_INT(mpx().."LFETIME_BIKER_BUY_UNDERTA2", 1025 + rn())
        STAT_SET_INT(mpx().."LFETIME_BIKER_SELL_COMPLET2", 1025 + rn())
        STAT_SET_INT(mpx().."LFETIME_BIKER_SELL_UNDERTA2", 1025 + rn())
        STAT_SET_INT(mpx().."LFETIME_BIKER_BUY_COMPLET3", 1025 + rn())
        STAT_SET_INT(mpx().."LFETIME_BIKER_BUY_UNDERTA3", 1025 + rn())
        STAT_SET_INT(mpx().."LFETIME_BIKER_SELL_COMPLET3", 1025 + rn())
        STAT_SET_INT(mpx().."LFETIME_BIKER_SELL_UNDERTA3", 1025 + rn())
        STAT_SET_INT(mpx().."LFETIME_BIKER_BUY_COMPLET4", 1025 + rn())
        STAT_SET_INT(mpx().."LFETIME_BIKER_BUY_UNDERTA4", 1025 + rn())
        STAT_SET_INT(mpx().."LFETIME_BIKER_SELL_COMPLET4", 1025 + rn())
        STAT_SET_INT(mpx().."LFETIME_BIKER_SELL_UNDERTA4", 1025 + rn())
        STAT_SET_INT(mpx().."LFETIME_BIKER_BUY_COMPLET5", 1025 + rn())
        STAT_SET_INT(mpx().."LFETIME_BIKER_BUY_UNDERTA5", 1025 + rn())
        STAT_SET_INT(mpx().."LFETIME_BIKER_SELL_COMPLET5", 1025 + rn())
        STAT_SET_INT(mpx().."LFETIME_BIKER_SELL_UNDERTA5", 1025 + rn())
        STAT_SET_INT(mpx().."LIFETIME_BKR_SELL_EARNINGS0", 25000000)
        STAT_SET_INT(mpx().."LIFETIME_BKR_SELL_EARNINGS1", 25000000)
        STAT_SET_INT(mpx().."LIFETIME_BKR_SELL_EARNINGS2", 25000000)
        STAT_SET_INT(mpx().."LIFETIME_BKR_SELL_EARNINGS3", 25000000)
        STAT_SET_INT(mpx().."LIFETIME_BKR_SELL_EARNINGS4", 25000000)
        STAT_SET_INT(mpx().."LFETIME_BIKER_BUY_COMPLET6", 10) 
        STAT_SET_INT(mpx().."LFETIME_BIKER_SELL_COMPLET6", 10) 
        STAT_SET_INT('MPPLY_CREW_NO_HEISTS_0', 2)
        STAT_SET_INT('MPPLY_CREW_NO_HEISTS_1', 5)
        STAT_SET_INT('MPPLY_CREW_NO_HEISTS_2', 5)
        STAT_SET_INT('MPPLY_CREW_NO_HEISTS_3', 5)
        STAT_SET_INT('MPPLY_CREW_NO_HEISTS_4', 5)
        STAT_SET_INT('MPPLY_GANGOPS_LOYALTY2', -1)
        STAT_SET_INT('MPPLY_GANGOPS_LOYALTY3', -1)
        STAT_SET_INT('MPPLY_GANGOPS_CRIMMASMD2', -1)
        STAT_SET_INT('MPPLY_GANGOPS_CRIMMASMD3', -1)
        STAT_SET_INT('MPPLY_GANGOPS_SUPPORT', -1)
        STAT_SET_INT('MPPLY_GANGOPS_ALLINORDER', -1)
        STAT_SET_INT('MPPLY_GANGOPS_LOYALTY', -1)
        STAT_SET_INT('MPPLY_GANGOPS_CRIMMASMD', -1)
        STAT_SET_INT('MPPLY_XMASLIVERIES0', -1)
        STAT_SET_INT('MPPLY_XMASLIVERIES1', -1)
        STAT_SET_INT('MPPLY_XMASLIVERIES2', -1)
        STAT_SET_INT('MPPLY_XMASLIVERIES3', -1)
        STAT_SET_INT('MPPLY_XMASLIVERIES4', -1)
        STAT_SET_INT('MPPLY_XMASLIVERIES5', -1)
        STAT_SET_INT('MPPLY_XMASLIVERIES6', -1)
        STAT_SET_INT('MPPLY_XMASLIVERIES7', -1)
        STAT_SET_INT('MPPLY_XMASLIVERIES8', -1)
        STAT_SET_INT('MPPLY_XMASLIVERIES9', -1)
        STAT_SET_INT('MPPLY_XMASLIVERIES10', -1)
        STAT_SET_INT('MPPLY_XMASLIVERIES11', -1)
        STAT_SET_INT('MPPLY_XMASLIVERIES12', -1)
        STAT_SET_INT('MPPLY_XMASLIVERIES13', -1)
        STAT_SET_INT('MPPLY_XMASLIVERIES14', -1)
        STAT_SET_INT('MPPLY_XMASLIVERIES15', -1)
        STAT_SET_INT('MPPLY_XMASLIVERIES16', -1)
        STAT_SET_INT('MPPLY_XMASLIVERIES17', -1)
        STAT_SET_INT('MPPLY_XMASLIVERIES18', -1)
        STAT_SET_INT('MPPLY_XMASLIVERIES19', -1)
        STAT_SET_INT('MPPLY_XMASLIVERIES20', -1)
        STAT_SET_INT(mpx()..'HOLDUPS_BITSET', -1)
        STAT_SET_INT(mpx()..'CHAR_ABILITY_1_UNLCK', -1)
        STAT_SET_INT(mpx()..'CHAR_ABILITY_2_UNLCK', -1)
        STAT_SET_INT(mpx()..'CHAR_ABILITY_3_UNLCK', -1)
        STAT_SET_INT(mpx()..'CHAR_WEAP_UNLOCKED', -1)
        STAT_SET_INT(mpx()..'CHAR_WEAP_UNLOCKED2', -1)
        STAT_SET_INT(mpx()..'CHAR_WEAP_ADDON_1_UNLCK', -1)
        STAT_SET_INT(mpx()..'CHAR_WEAP_ADDON_2_UNLCK', -1)
        STAT_SET_INT(mpx()..'CHAR_WEAP_ADDON_3_UNLCK', -1)
        STAT_SET_INT(mpx()..'CHAR_WEAP_ADDON_4_UNLCK', -1)
        STAT_SET_INT(mpx()..'CHAR_FM_WEAP_UNLOCKED', -1)
        STAT_SET_INT(mpx()..'CHAR_FM_WEAP_UNLOCKED2', -1)
        STAT_SET_INT(mpx()..'CHAR_FM_WEAP_UNLOCKED3', -1)
        STAT_SET_INT(mpx()..'CHAR_FM_WEAP_UNLOCKED4', -1)
        STAT_SET_INT(mpx()..'CHAR_FM_WEAP_UNLOCKED5', -1)
        STAT_SET_INT(mpx()..'CHAR_FM_WEAP_ADDON_1_UNLCK', -1)
        STAT_SET_INT(mpx()..'CHAR_FM_WEAP_ADDON_2_UNLCK', -1)
        STAT_SET_INT(mpx()..'CHAR_FM_WEAP_ADDON_3_UNLCK', -1)
        STAT_SET_INT(mpx()..'CHAR_FM_WEAP_ADDON_4_UNLCK', -1)
        STAT_SET_INT(mpx()..'CHAR_FM_WEAP_ADDON_5_UNLCK', -1)
        STAT_SET_INT(mpx()..'CHAR_FM_WEAP_ADDON_6_UNLCK', -1)
        STAT_SET_INT(mpx()..'CHAR_FM_WEAP_ADDON_7_UNLCK', -1)
        STAT_SET_INT(mpx()..'CHAR_FM_WEAP_ADDON_8_UNLCK', -1)
        STAT_SET_INT(mpx()..'CHAR_FM_WEAP_ADDON_9_UNLCK', -1)
        STAT_SET_INT(mpx()..'CHAR_FM_WEAP_ADDON_10_UNLCK', -1)
        STAT_SET_INT(mpx()..'CHAR_FM_WEAP_ADDON_11_UNLCK', -1)
        STAT_SET_INT(mpx()..'CHAR_FM_WEAP_ADDON_12_UNLCK', -1)
        STAT_SET_INT(mpx()..'CHAR_FM_WEAP_ADDON_13_UNLCK', -1)
        STAT_SET_INT(mpx()..'CHAR_FM_WEAP_ADDON_14_UNLCK', -1)
        STAT_SET_INT(mpx()..'CHAR_FM_WEAP_ADDON_15_UNLCK', -1)
        STAT_SET_INT(mpx()..'CHAR_FM_WEAP_ADDON_16_UNLCK', -1)
        STAT_SET_INT(mpx()..'CHAR_FM_WEAP_ADDON_17_UNLCK', -1)
        STAT_SET_INT(mpx()..'CHAR_FM_WEAP_ADDON_18_UNLCK', -1)
        STAT_SET_INT(mpx()..'CHAR_FM_WEAP_ADDON_19_UNLCK', -1)
        STAT_SET_INT(mpx()..'CHAR_FM_WEAP_ADDON_20_UNLCK', -1)
        STAT_SET_INT(mpx()..'CHAR_FM_HAIRCUT_1_UNLCK', -1)
        STAT_SET_INT(mpx()..'CHAR_HAIR_UNLCK1', -1)
        STAT_SET_INT(mpx()..'CHAR_HAIR_UNLCK2', -1)
        STAT_SET_INT(mpx()..'CHAR_HAIR_UNLCK3', -1)
        STAT_SET_INT(mpx()..'CHAR_HAIR_UNLCK4', -1)
        STAT_SET_INT(mpx()..'CHAR_HAIR_UNLCK5', -1)
        STAT_SET_INT(mpx()..'CHAR_HAIR_UNLCK6', -1)
        STAT_SET_INT(mpx()..'CHAR_HAIR_UNLCK7', -1)
        STAT_SET_INT(mpx()..'CHAR_HAIR_UNLCK8', -1)
        STAT_SET_INT(mpx()..'CHAR_HAIR_UNLCK9', -1)
        STAT_SET_INT(mpx()..'CHAR_HAIR_UNLCK10', -1)
        STAT_SET_INT(mpx()..'CHAR_HAIR_UNLCK11', -1)
        STAT_SET_INT(mpx()..'CHAR_HAIR_UNLCK12', -1)
        STAT_SET_INT(mpx()..'CHAR_HAIR_UNLCK13', -1)
        STAT_SET_INT(mpx()..'CHAR_HAIR_UNLCK14', -1)
        STAT_SET_INT(mpx()..'CHAR_HAIR_UNLCK15', -1)
        STAT_SET_INT(mpx()..'CHAR_HAIR_UNLCK16', -1)
        STAT_SET_INT(mpx()..'CHAR_HAIR_UNLCK17', -1)
        STAT_SET_INT(mpx()..'CHAR_FM_HEALTH_1_UNLCK', -1)
        STAT_SET_INT(mpx()..'CHAR_FM_HEALTH_2_UNLCK', -1)
        STAT_SET_INT(mpx()..'CRDEADLINE', 5)
        STAT_SET_INT(mpx()..'CHAR_CREWUNLOCK_1_FM_EQUIP', -1)
        STAT_SET_INT(mpx()..'CHAR_CREWUNLOCK_2_FM_EQUIP', -1)
        STAT_SET_INT(mpx()..'CHAR_CREWUNLOCK_3_FM_EQUIP', -1)
        STAT_SET_INT(mpx()..'CHAR_CREWUNLOCK_4_FM_EQUIP', -1)
        STAT_SET_INT(mpx()..'CHAR_CREWUNLOCK_5_FM_EQUIP', -1)
        STAT_SET_INT(mpx()..'CHAR_KIT_1_FM_UNLCK', -1)
        STAT_SET_INT(mpx()..'CHAR_KIT_2_FM_UNLCK', -1)
        STAT_SET_INT(mpx()..'CHAR_KIT_3_FM_UNLCK', -1)
        STAT_SET_INT(mpx()..'CHAR_KIT_4_FM_UNLCK', -1)
        STAT_SET_INT(mpx()..'CHAR_KIT_5_FM_UNLCK', -1)
        STAT_SET_INT(mpx()..'CHAR_KIT_6_FM_UNLCK', -1)
        STAT_SET_INT(mpx()..'CHAR_KIT_7_FM_UNLCK', -1)
        STAT_SET_INT(mpx()..'CHAR_KIT_8_FM_UNLCK', -1)
        STAT_SET_INT(mpx()..'CHAR_KIT_9_FM_UNLCK', -1)
        STAT_SET_INT(mpx()..'CHAR_KIT_10_FM_UNLCK', -1)
        STAT_SET_INT(mpx()..'CHAR_KIT_11_FM_UNLCK', -1)
        STAT_SET_INT(mpx()..'CHAR_KIT_12_FM_UNLCK', -1)
        STAT_SET_INT(mpx()..'CHAR_KIT_13_FM_UNLCK', -1)
        STAT_SET_INT(mpx()..'CHAR_KIT_14_FM_UNLCK', -1)
        STAT_SET_INT(mpx()..'CHAR_KIT_15_FM_UNLCK', -1)
        STAT_SET_INT(mpx()..'CHAR_KIT_16_FM_UNLCK', -1)
        STAT_SET_INT(mpx()..'CHAR_KIT_17_FM_UNLCK', -1)
        STAT_SET_INT(mpx()..'CHAR_KIT_18_FM_UNLCK', -1)
        STAT_SET_INT(mpx()..'CHAR_KIT_19_FM_UNLCK', -1)
        STAT_SET_INT(mpx()..'CHAR_KIT_20_FM_UNLCK', -1)
        STAT_SET_INT(mpx()..'CHAR_KIT_21_FM_UNLCK', -1)
        STAT_SET_INT(mpx()..'CHAR_KIT_22_FM_UNLCK', -1)
        STAT_SET_INT(mpx()..'CHAR_KIT_23_FM_UNLCK', -1)
        STAT_SET_INT(mpx()..'CHAR_KIT_24_FM_UNLCK', -1)
        STAT_SET_INT(mpx()..'CHAR_KIT_25_FM_UNLCK', -1)
        STAT_SET_INT(mpx()..'CHAR_KIT_26_FM_UNLCK', -1)
        STAT_SET_INT(mpx()..'CHAR_KIT_27_FM_UNLCK', -1)
        STAT_SET_INT(mpx()..'CHAR_KIT_28_FM_UNLCK', -1)
        STAT_SET_INT(mpx()..'CHAR_KIT_29_FM_UNLCK', -1)
        STAT_SET_INT(mpx()..'CHAR_KIT_30_FM_UNLCK', -1)
        STAT_SET_INT(mpx()..'CHAR_KIT_30_FM_UNLCK', -1)
        STAT_SET_INT(mpx()..'CHAR_KIT_31_FM_UNLCK', -1)
        STAT_SET_INT(mpx()..'CHAR_KIT_32_FM_UNLCK', -1)
        STAT_SET_INT(mpx()..'CHAR_KIT_33_FM_UNLCK', -1)
        STAT_SET_INT(mpx()..'CHAR_KIT_34_FM_UNLCK', -1)
        STAT_SET_INT(mpx()..'CHAR_KIT_35_FM_UNLCK', -1)
        STAT_SET_INT(mpx()..'CHAR_KIT_36_FM_UNLCK', -1)
        STAT_SET_INT(mpx()..'CHAR_KIT_37_FM_UNLCK', -1)
        STAT_SET_INT(mpx()..'CHAR_KIT_38_FM_UNLCK', -1)
        STAT_SET_INT(mpx()..'CHAR_KIT_39_FM_UNLCK', -1)
        STAT_SET_INT(mpx()..'CHAR_KIT_40_FM_UNLCK', -1)
        STAT_SET_INT(mpx()..'CHAR_KIT_41_FM_UNLCK', -1)
        STAT_SET_INT(mpx()..'CHAR_FM_ABILITY_1_UNLCK', -1)
        STAT_SET_INT(mpx()..'CHAR_FM_ABILITY_2_UNLCK', -1)
        STAT_SET_INT(mpx()..'CHAR_FM_ABILITY_3_UNLCK', -1)
        STAT_SET_INT(mpx()..'CHAR_FM_CLOTHES_1_UNLCK', -1)
        STAT_SET_INT(mpx()..'CHAR_FM_CLOTHES_2_UNLCK', -1)
        STAT_SET_INT(mpx()..'CHAR_FM_CLOTHES_3_UNLCK', -1)
        STAT_SET_INT(mpx()..'CHAR_FM_CLOTHES_4_UNLCK', -1)
        STAT_SET_INT(mpx()..'CHAR_FM_CLOTHES_5_UNLCK', -1)
        STAT_SET_INT(mpx()..'CHAR_FM_CLOTHES_6_UNLCK', -1)
        STAT_SET_INT(mpx()..'CHAR_FM_CLOTHES_7_UNLCK', -1)
        STAT_SET_INT(mpx()..'CHAR_FM_CLOTHES_8_UNLCK', -1)
        STAT_SET_INT(mpx()..'CHAR_FM_CLOTHES_9_UNLCK', -1)
        STAT_SET_INT(mpx()..'CHAR_FM_CLOTHES_10_UNLCK', -1)
        STAT_SET_INT(mpx()..'CHAR_FM_CLOTHES_11_UNLCK', -1)
        STAT_SET_INT(mpx()..'CHAR_FM_VEHICLE_1_UNLCK', -1)
        STAT_SET_INT(mpx()..'CHAR_FM_VEHICLE_2_UNLCK', -1)
        STAT_SET_INT(mpx()..'TATTOO_FM_UNLOCKS_0', -1)
        STAT_SET_INT(mpx()..'TATTOO_FM_UNLOCKS_1', -1)
        STAT_SET_INT(mpx()..'TATTOO_FM_UNLOCKS_2', -1)
        STAT_SET_INT(mpx()..'TATTOO_FM_UNLOCKS_3', -1)
        STAT_SET_INT(mpx()..'TATTOO_FM_UNLOCKS_4', -1)
        STAT_SET_INT(mpx()..'TATTOO_FM_UNLOCKS_5', -1)
        STAT_SET_INT(mpx()..'TATTOO_FM_UNLOCKS_6', -1)
        STAT_SET_INT(mpx()..'TATTOO_FM_UNLOCKS_7', -1)
        STAT_SET_INT(mpx()..'TATTOO_FM_UNLOCKS_8', -1)
        STAT_SET_INT(mpx()..'TATTOO_FM_UNLOCKS_9', -1)
        STAT_SET_INT(mpx()..'TATTOO_FM_UNLOCKS_10', -1)
        STAT_SET_INT(mpx()..'TATTOO_FM_UNLOCKS_11', -1)
        STAT_SET_INT(mpx()..'TATTOO_FM_UNLOCKS_12', -1)
        STAT_SET_INT(mpx()..'TATTOO_FM_UNLOCKS_13', -1)
        STAT_SET_INT(mpx()..'TATTOO_FM_UNLOCKS_14', -1)
        STAT_SET_INT(mpx()..'TATTOO_FM_UNLOCKS_15', -1)
        STAT_SET_INT(mpx()..'TATTOO_FM_UNLOCKS_16', -1)
        STAT_SET_INT(mpx()..'TATTOO_FM_UNLOCKS_17', -1)
        STAT_SET_INT(mpx()..'TATTOO_FM_UNLOCKS_18', -1)
        STAT_SET_INT(mpx()..'TATTOO_FM_UNLOCKS_19', -1)
        STAT_SET_INT(mpx()..'TATTOO_FM_UNLOCKS_20', -1)
        STAT_SET_INT(mpx()..'TATTOO_FM_UNLOCKS_21', -1)
        STAT_SET_INT(mpx()..'TATTOO_FM_UNLOCKS_22', -1)
        STAT_SET_INT(mpx()..'TATTOO_FM_UNLOCKS_23', -1)
        STAT_SET_INT(mpx()..'TATTOO_FM_UNLOCKS_24', -1)
        STAT_SET_INT(mpx()..'TATTOO_FM_UNLOCKS_25', -1)
        STAT_SET_INT(mpx()..'TATTOO_FM_UNLOCKS_26', -1)
        STAT_SET_INT(mpx()..'TATTOO_FM_UNLOCKS_27', -1)
        STAT_SET_INT(mpx()..'TATTOO_FM_UNLOCKS_28', -1)
        STAT_SET_INT(mpx()..'TATTOO_FM_UNLOCKS_29', -1)
        STAT_SET_INT(mpx()..'TATTOO_FM_UNLOCKS_30', -1)
        STAT_SET_INT(mpx()..'TATTOO_FM_UNLOCKS_31', -1)
        STAT_SET_INT(mpx()..'TATTOO_FM_UNLOCKS_32', -1)
        STAT_SET_INT(mpx()..'TATTOO_FM_UNLOCKS_33', -1)
        STAT_SET_INT(mpx()..'TATTOO_FM_UNLOCKS_34', -1)
        STAT_SET_INT(mpx()..'TATTOO_FM_UNLOCKS_35', -1)
        STAT_SET_INT(mpx()..'TATTOO_FM_UNLOCKS_36', -1)
        STAT_SET_INT(mpx()..'TATTOO_FM_UNLOCKS_37', -1)
        STAT_SET_INT(mpx()..'TATTOO_FM_UNLOCKS_38', -1)
        STAT_SET_INT(mpx()..'TATTOO_FM_UNLOCKS_39', -1)
        STAT_SET_INT(mpx()..'TATTOO_FM_UNLOCKS_40', -1)
        STAT_SET_INT(mpx()..'TATTOO_FM_UNLOCKS_41', -1)
        STAT_SET_INT(mpx()..'TATTOO_FM_UNLOCKS_42', -1)
        STAT_SET_INT(mpx()..'TATTOO_FM_UNLOCKS_43', -1)
        STAT_SET_INT(mpx()..'TATTOO_FM_UNLOCKS_44', -1)
        STAT_SET_INT(mpx()..'TATTOO_FM_UNLOCKS_45', -1)
        STAT_SET_INT(mpx()..'TATTOO_FM_UNLOCKS_46', -1)
        STAT_SET_INT(mpx()..'TATTOO_FM_UNLOCKS_47', -1)
        STAT_SET_INT(mpx()..'TATTOO_FM_UNLOCKS_48', -1)
        STAT_SET_INT(mpx()..'TATTOO_FM_UNLOCKS_49', -1)
        STAT_SET_INT(mpx()..'TATTOO_FM_UNLOCKS_50', -1)
        STAT_SET_INT(mpx()..'TATTOO_FM_UNLOCKS_51', -1)
        STAT_SET_INT(mpx()..'TATTOO_FM_UNLOCKS_52', -1)
        STAT_SET_INT(mpx()..'TATTOO_FM_UNLOCKS_53', -1)
        STAT_SET_INT(mpx()..'RANKAP_UNLK_0', -1)
        STAT_SET_INT(mpx()..'RANKAP_UNLK_1', -1)
        STAT_SET_INT(mpx()..'RANKAP_UNLK_2', -1)
        STAT_SET_INT(mpx()..'RANKAP_UNLK_3', -1)
        STAT_SET_INT(mpx()..'CHAR_CREWUNLOCK_1_UNLCK', -1)
        STAT_SET_INT(mpx()..'SR_WEAPON_BIT_SET', -1)
        STAT_SET_INT(mpx()..'CAR_CLUB_REP', 997430)
        STAT_SET_BOOL(mpx()..'SR_TIER_1_REWARD', true)
        STAT_SET_BOOL(mpx()..'SR_INCREASE_THROW_CAP', true)
        STAT_SET_BOOL(mpx()..'SR_TIER_3_REWARD', true)
        STAT_SET_BOOL('MPPLY_MELEECHLENGECOMPLETED', true)
        STAT_SET_BOOL('MPPLY_HEADSHOTCHLENGECOMPLETED', true)
        STAT_SET_INT(mpx()..'CHAR_HEIST_1_UNLCK', -1)
        STAT_SET_INT(mpx()..'CHAR_FM_VEHICLE_1_UNLCK', -1)
        STAT_SET_INT(mpx()..'CHAR_FM_VEHICLE_2_UNLCK', -1)
        STAT_SET_INT(mpx()..'CRHEIST', 50)
        STAT_SET_INT(mpx()..'CR_BANKHEIST1', 10)
        STAT_SET_INT(mpx()..'CR_COUNTHEIST1', 10)
        STAT_SET_INT(mpx()..'HEIST_COMPLETION', 26)
        STAT_SET_INT(mpx()..'HEIST_TOTAL_TIME', 86400000)
        STAT_SET_INT(mpx()..'HEISTS_ORGANISED', 50)

        STAT_SET_INT(mpx()..'CHAR_FM_PACKAGE_1_COLLECT', -1)
        STAT_SET_INT(mpx()..'CHAR_FM_PACKAGE_2_COLLECT', -1)
        STAT_SET_INT(mpx()..'CHAR_FM_PACKAGE_3_COLLECT', -1)
        STAT_SET_INT(mpx()..'CHAR_FM_PACKAGE_4_COLLECT', -1)
        STAT_SET_INT(mpx()..'CHAR_FM_PACKAGE_5_COLLECT', -1)
        STAT_SET_INT(mpx()..'CHAR_FM_PACKAGE_6_COLLECT', -1)
        STAT_SET_INT(mpx()..'CHAR_FM_PACKAGE_7_COLLECT', -1)
        STAT_SET_INT(mpx()..'CHAR_FM_PACKAGE_8_COLLECT', -1)
        STAT_SET_INT(mpx()..'CHAR_NO_FM_PACKAGES_COL', -1)
        STAT_SET_INT(mpx()..'CHAR_FM_CARMOD_1_UNLCK', -1)
        STAT_SET_INT(mpx()..'CHAR_FM_CARMOD_2_UNLCK', -1)
        STAT_SET_INT(mpx()..'CHAR_FM_CARMOD_3_UNLCK', -1)
        STAT_SET_INT(mpx()..'CHAR_FM_CARMOD_4_UNLCK', -1)
        STAT_SET_INT(mpx()..'CHAR_FM_CARMOD_5_UNLCK', -1)
        STAT_SET_INT(mpx()..'CHAR_FM_CARMOD_6_UNLCK', -1)
        STAT_SET_INT(mpx()..'CHAR_FM_CARMOD_7_UNLCK', -1)

        STAT_SET_INT(mpx()..'RACES_WON', 345+ rn())
        STAT_SET_INT(mpx()..'NUMBER_SLIPSTREAMS_IN_RACE', 213+ rn())
        STAT_SET_INT(mpx()..'NUMBER_TURBO_STARTS_IN_RACE', 200+ rn())
        STAT_SET_INT(mpx()..'MPPLY_TIMES_RACE_BEST_LAP', 300+ rn())
        STAT_SET_INT(mpx()..'AWD_FMRALLYWONDRIVE', 25+ rn())
        STAT_SET_INT(mpx()..'AWD_FMWINSEARACE', 144+ rn())
        STAT_SET_INT(mpx()..'AWD_FMWINAIRRACE', 76 + rn())
        STAT_SET_INT(mpx()..'AWD_FM_RACES_FASTEST_LAP', 201+ rn())

		
		STAT_SET_INT(mpx()..'USJS_FOUND', 50+ rn())
        STAT_SET_INT(mpx()..'USJS_COMPLETED', 50+ rn())
        STAT_SET_INT(mpx()..'SCRIPT_INCREASE_STAM', 100)
        STAT_SET_INT(mpx()..'SCRIPT_INCREASE_STRN', 100)
        STAT_SET_INT(mpx()..'SCRIPT_INCREASE_FLY', 100)
        STAT_SET_INT(mpx()..'SCRIPT_INCREASE_STL', 100)
        STAT_SET_INT(mpx()..'SCRIPT_INCREASE_LUNG', 100)
        STAT_SET_INT(mpx()..'SCRIPT_INCREASE_DRIV', 100)
        STAT_SET_INT(mpx()..'SCRIPT_INCREASE_SHO', 100)
        STAT_SET_INT(mpx()..'AWD_DANCE_TO_SOLOMUN', 360)
        STAT_SET_INT('NIGHTCLUB_HOTSPOT_TIME_MS', 3600000)
        STAT_SET_INT(mpx()..'CASINO_DECORATION_GIFT_1', -1);
        STAT_SET_BOOL(mpx()..'COMPLETE_H4_F_USING_VETIR', true);
        STAT_SET_BOOL(mpx()..'COMPLETE_H4_F_USING_LONGFIN', true);
        STAT_SET_BOOL(mpx()..'COMPLETE_H4_F_USING_ANNIH', true);
        STAT_SET_BOOL(mpx()..'COMPLETE_H4_F_USING_ALKONOS', true);
        STAT_SET_BOOL(mpx()..'COMPLETE_H4_F_USING_PATROLB', true);
        STAT_SET_BOOL(mpx()..'AWD_DEADEYE', true)
		STAT_SET_BOOL(mpx()..'AWD_PISTOLSATDAWN', true)
		STAT_SET_BOOL(mpx()..'AWD_TRAFFICAVOI', true)
		STAT_SET_BOOL(mpx()..'AWD_CANTCATCHBRA', true)
		STAT_SET_BOOL(mpx()..'AWD_WIZHARD', true)
		STAT_SET_BOOL(mpx()..'AWD_APEESCAPE', true)
		STAT_SET_BOOL(mpx()..'AWD_MONKEYKIND', true)
		STAT_SET_BOOL(mpx()..'AWD_AQUAAPE', true)
		STAT_SET_BOOL(mpx()..'AWD_KEEPFAITH', true)
		STAT_SET_BOOL(mpx()..'AWD_TRUELOVE', true)
		STAT_SET_BOOL(mpx()..'AWD_NEMESIS', true)
		STAT_SET_BOOL(mpx()..'AWD_FRIENDZONED', true)
		STAT_SET_BOOL(mpx()..'SCGW_WON_NO_DEATHS', true)
		STAT_SET_BOOL(mpx()..'IAP_CHALLENGE_0', true)
		STAT_SET_BOOL(mpx()..'IAP_CHALLENGE_1', true)
		STAT_SET_BOOL(mpx()..'IAP_CHALLENGE_2', true)
		STAT_SET_BOOL(mpx()..'IAP_CHALLENGE_3', true)
		STAT_SET_BOOL(mpx()..'IAP_CHALLENGE_4', true)
		STAT_SET_BOOL(mpx()..'AWD_KINGOFQUB3D', true)
		STAT_SET_BOOL(mpx()..'AWD_QUBISM', true)
		STAT_SET_BOOL(mpx()..'AWD_GODOFQUB3D', true)
		STAT_SET_BOOL(mpx()..'AWD_QUIBITS', true)
		STAT_SET_BOOL(mpx()..'AWD_ELEVENELEVEN', true)
		STAT_SET_BOOL(mpx()..'AWD_GOFOR11TH', true)
		STAT_SET_BOOL(mpx()..'AWD_STRAIGHT_TO_VIDEO', true)
		STAT_SET_BOOL(mpx()..'AWD_MONKEY_C_MONKEY_DO', true)
		STAT_SET_BOOL(mpx()..'AWD_TRAINED_TO_KILL', true)
		STAT_SET_BOOL(mpx()..'AWD_DIRECTOR', true)
		STAT_SET_INT(mpx()..'AWD_SHARPSHOOTER', 40)
		STAT_SET_INT(mpx()..'AWD_RACECHAMP', 40)
		
				
	  STAT_SET_INT(mpx().."AWD_DROPOFF_CAP_PACKAGES", 100)
	  STAT_SET_INT(mpx().."AWD_KILL_CARRIER_CAPTURE", 100)
	  STAT_SET_INT(mpx().."AWD_FINISH_HEISTS", 50)
	  STAT_SET_INT(mpx().."AWD_FINISH_HEIST_SETUP_JOB", 50)
	  STAT_SET_INT(mpx().."AWD_NIGHTVISION_KILLS", 100)
	  STAT_SET_INT(mpx().."AWD_WIN_LAST_TEAM_STANDINGS", 50)
	  STAT_SET_INT(mpx().."AWD_ONLY_PLAYER_ALIVE_LTS", 50)
	  STAT_SET_INT(mpx().."AWD_TAXIDRIVER", 100)
		

		
		STAT_SET_INT(mpx().."AWD_WIN_CAPTURES", 50)
		
		for i = 1, 20 do
			STAT_SET_INT(mpx().. "MPPLY_XMASLIVERIES" .. (i + 100), 1)
			STAT_SET_INT("MPPLY_XMASLIVERIES" .. (i + 100), 1)
		end
				
		UnlockALLparachutes()
		

		STAT_SET_MASKED_BOOL(mpx() .. "FIXERPSTAT_BOOL0", true, 4) 
		STAT_SET_MASKED_BOOL(mpx() .. "DLC12022PSTAT_BOOL7", true, 62) 
		STAT_SET_MASKED_BOOL(mpx() .. "DLC12023PSTAT_BOOL11", true, 49)
		STAT_SET_MASKED_BOOL(mpx() .. "DLC12023PSTAT_BOOL11", true, 50)
		STAT_SET_MASKED_BOOL(mpx() .. "DLC22023PSTAT_BOOL0", true, 14)
		STAT_SET_MASKED_BOOL(mpx() .. "DLC22023PSTAT_BOOL0", true, 15)
		STAT_SET_MASKED_BOOL(mpx() .. "DLC22023PSTAT_BOOL0", true, 16)
		

		records = {
			{ stat = "TUNERPSTAT_BOOL0", index = 1 },
			{ stat = "TUNERPSTAT_BOOL0", index = 2 },
			{ stat = "TUNERPSTAT_BOOL0", index = 3 },
			{ stat = "TUNERPSTAT_BOOL0", index = 4 },
			{ stat = "TUNERPSTAT_BOOL0", index = 5 },
			{ stat = "TUNERPSTAT_BOOL0", index = 6 },
			{ stat = "TUNERPSTAT_BOOL0", index = 7 }
		}

		for _, record in ipairs(records) do
			STAT_SET_MASKED_BOOL(mpx() .. record.stat, true, record.index)
		end
			
			
		STAT_SET_INT(mpx() .. "CHAR_WEAP_UNLOCKED", -1)
		STAT_SET_INT(mpx() .. "CHAR_WEAP_UNLOCKED2", -1)
		STAT_SET_INT(mpx() .. "CHAR_WEAP_UNLOCKED3", -1)
		STAT_SET_INT(mpx() .. "CHAR_WEAP_UNLOCKED4", -1)
		STAT_SET_INT(mpx() .. "CHAR_WEAP_ADDON_1_UNLCK", -1)
		STAT_SET_INT(mpx() .. "CHAR_WEAP_ADDON_2_UNLCK", -1)
		STAT_SET_INT(mpx() .. "CHAR_WEAP_ADDON_3_UNLCK", -1)
		STAT_SET_INT(mpx() .. "CHAR_WEAP_ADDON_4_UNLCK", -1)
		STAT_SET_INT(mpx() .. "CHAR_WEAP_FREE", -1)
		STAT_SET_INT(mpx() .. "CHAR_WEAP_FREE2", -1)
		STAT_SET_INT(mpx() .. "CHAR_FM_WEAP_FREE", -1)
		STAT_SET_INT(mpx() .. "CHAR_FM_WEAP_FREE2", -1)
		STAT_SET_INT(mpx() .. "CHAR_FM_WEAP_FREE3", -1)
		STAT_SET_INT(mpx() .. "CHAR_FM_WEAP_FREE4", -1)
		STAT_SET_INT(mpx() .. "CHAR_WEAP_PURCHASED", -1)
		STAT_SET_INT(mpx() .. "CHAR_WEAP_PURCHASED2", -1)
		STAT_SET_INT(mpx() .. "WEAPON_PICKUP_BITSET", -1)
		STAT_SET_INT(mpx() .. "WEAPON_PICKUP_BITSET2", -1)
		STAT_SET_INT(mpx() .. "CHAR_FM_WEAP_UNLOCKED", -1)
		STAT_SET_INT(mpx() .. "NO_WEAPONS_UNLOCK", -1)
		STAT_SET_INT(mpx() .. "NO_WEAPON_MODS_UNLOCK", -1)
		STAT_SET_INT(mpx() .. "NO_WEAPON_CLR_MOD_UNLOCK", -1) 
		STAT_SET_INT(mpx() .. "CHAR_FM_WEAP_UNLOCKED2", -1)
		STAT_SET_INT(mpx() .. "CHAR_FM_WEAP_UNLOCKED3", -1)
		STAT_SET_INT(mpx() .. "CHAR_FM_WEAP_UNLOCKED4", -1)
		STAT_SET_INT(mpx() .. "CHAR_KIT_1_FM_UNLCK", -1)
		STAT_SET_INT(mpx() .. "CHAR_KIT_2_FM_UNLCK", -1)
		STAT_SET_INT(mpx() .. "CHAR_KIT_3_FM_UNLCK", -1)
		STAT_SET_INT(mpx() .. "CHAR_KIT_4_FM_UNLCK", -1)
		STAT_SET_INT(mpx() .. "CHAR_KIT_5_FM_UNLCK", -1)
		STAT_SET_INT(mpx() .. "CHAR_KIT_6_FM_UNLCK", -1)
		STAT_SET_INT(mpx() .. "CHAR_KIT_7_FM_UNLCK", -1)
		STAT_SET_INT(mpx() .. "CHAR_KIT_8_FM_UNLCK", -1)
		STAT_SET_INT(mpx() .. "CHAR_KIT_9_FM_UNLCK", -1)
		STAT_SET_INT(mpx() .. "CHAR_KIT_10_FM_UNLCK", -1)
		STAT_SET_INT(mpx() .. "CHAR_KIT_11_FM_UNLCK", -1)
		STAT_SET_INT(mpx() .. "CHAR_KIT_12_FM_UNLCK", -1)
		STAT_SET_INT(mpx() .. "CHAR_KIT_FM_PURCHASE", -1)
		STAT_SET_INT(mpx() .. "CHAR_WEAP_FM_PURCHASE", -1)
		STAT_SET_INT(mpx() .. "CHAR_WEAP_FM_PURCHASE2", -1)
		STAT_SET_INT(mpx() .. "CHAR_WEAP_FM_PURCHASE3", -1)
		STAT_SET_INT(mpx() .. "CHAR_WEAP_FM_PURCHASE4", -1)
		STAT_SET_INT(mpx() .. "FIREWORK_TYPE_1_WHITE", 1000)
		STAT_SET_INT(mpx() .. "FIREWORK_TYPE_1_RED", 1000)
		STAT_SET_INT(mpx() .. "FIREWORK_TYPE_1_BLUE", 1000)
		STAT_SET_INT(mpx() .. "FIREWORK_TYPE_2_WHITE", 1000)
		STAT_SET_INT(mpx() .. "FIREWORK_TYPE_2_RED", 1000)
		STAT_SET_INT(mpx() .. "FIREWORK_TYPE_2_BLUE", 1000)
		STAT_SET_INT(mpx() .. "FIREWORK_TYPE_3_WHITE", 1000)
		STAT_SET_INT(mpx() .. "FIREWORK_TYPE_3_RED", 1000)
		STAT_SET_INT(mpx() .. "FIREWORK_TYPE_3_BLUE", 1000)
		STAT_SET_INT(mpx() .. "FIREWORK_TYPE_4_WHITE", 1000)
		STAT_SET_INT(mpx() .. "FIREWORK_TYPE_4_RED", 1000)
		STAT_SET_INT(mpx() .. "FIREWORK_TYPE_4_BLUE", 1000)
		STAT_SET_INT(mpx() .. "WEAP_FM_ADDON_PURCH", -1)
		
		STAT_SET_INT("MPPLY_XMAS23_PLATES0", -1)
		
		STAT_SET_MASKED_BOOL(mpx() .. "DLC12022PSTAT_BOOL7", true, 62) 
		STAT_SET_MASKED_BOOL(mpx() .. "DLC12023PSTAT_BOOL11", true, 49)
		STAT_SET_MASKED_BOOL(mpx() .. "DLC12023PSTAT_BOOL11", true, 50)
		STAT_SET_MASKED_BOOL(mpx() .. "DLC22023PSTAT_BOOL0", true, 14)
		STAT_SET_MASKED_BOOL(mpx() .. "DLC22023PSTAT_BOOL0", true, 15)
		STAT_SET_MASKED_BOOL(mpx() .. "DLC22023PSTAT_BOOL0", true, 16)
		
		STAT_SET_INT(mpx() .. "FM_ACT_PHN", -1)
		STAT_SET_INT(mpx() .. "FM_ACT_PH2", -1)
		STAT_SET_INT(mpx() .. "FM_ACT_PH3", -1)
		STAT_SET_INT(mpx() .. "FM_ACT_PH4", -1)
		STAT_SET_INT(mpx() .. "FM_ACT_PH5", -1)
		STAT_SET_INT(mpx() .. "FM_VEH_TX1", -1)
		STAT_SET_INT(mpx() .. "FM_ACT_PH6", -1)
		STAT_SET_INT(mpx() .. "FM_ACT_PH7", -1)
		STAT_SET_INT(mpx() .. "FM_ACT_PH8", -1)
		STAT_SET_INT(mpx() .. "FM_ACT_PH9", -1)
		STAT_SET_INT(mpx() .. "FM_CUT_DONE", -1)
		STAT_SET_INT(mpx() .. "FM_CUT_DONE_2", -1)
		
	   for i = 2, 19 do STAT_SET_INT(mpx() .. "WEAP_FM_ADDON_PURCH"..i, -1) end
	   for j = 1, 19 do STAT_SET_INT(mpx() .. "CHAR_FM_WEAP_ADDON_"..j.."_UNLCK", -1) end
	   for m = 1, 41 do STAT_SET_INT(mpx() .. "CHAR_KIT_"..m.."_FM_UNLCK", -1) end
	   for l = 2, 41 do STAT_SET_INT(mpx() .. "CHAR_KIT_FM_PURCHASE"..l, -1) end
	   
	   
	   
	   	local SecretAwards = {36068, 36069, 36070, 36071, 36072, 36073, 36074, 36075, 36305, 36306}
		for _, tunable in ipairs(SecretAwards) do
			STAT_SET_INT(262145 + tunable, 1)
		end
		STAT_SET_BOOL(42148,true) -- Unlock Snow launcher weapon
		STAT_SET_INT(262145+36250,1) --Get christmas gift 1"
		STAT_SET_INT(262145+36251,1) --Get christmas gift 2
		
		

		local statKeys = {
			"stam", "strn", "lung", "driv", "fly", "sho", "stl", "mech"
		}

		for _, key in ipairs(statKeys) do
			STAT_SET_INT(mpx() .. "script_increase_" .. key, 100)
		end
		
		
end



function UnlockVehicleOptions()
	STAT_SET_INT(mpx()..'CHAR_FM_PACKAGE_1_COLLECT', -1)
	STAT_SET_INT(mpx()..'CHAR_FM_PACKAGE_2_COLLECT', -1)
	STAT_SET_INT(mpx()..'CHAR_FM_PACKAGE_3_COLLECT', -1)
	STAT_SET_INT(mpx()..'CHAR_FM_PACKAGE_4_COLLECT', -1)
	STAT_SET_INT(mpx()..'CHAR_FM_PACKAGE_5_COLLECT', -1)
	STAT_SET_INT(mpx()..'CHAR_FM_PACKAGE_6_COLLECT', -1)
	STAT_SET_INT(mpx()..'CHAR_FM_PACKAGE_7_COLLECT', -1)
	STAT_SET_INT(mpx()..'CHAR_FM_PACKAGE_8_COLLECT', -1)
	STAT_SET_INT(mpx()..'CHAR_NO_FM_PACKAGES_COL', -1)
	STAT_SET_INT(mpx()..'CHAR_FM_CARMOD_1_UNLCK', -1)
	STAT_SET_INT(mpx()..'CHAR_FM_CARMOD_2_UNLCK', -1)
	STAT_SET_INT(mpx()..'CHAR_FM_CARMOD_3_UNLCK', -1)
	STAT_SET_INT(mpx()..'CHAR_FM_CARMOD_4_UNLCK', -1)
	STAT_SET_INT(mpx()..'CHAR_FM_CARMOD_5_UNLCK', -1)
	STAT_SET_INT(mpx()..'CHAR_FM_CARMOD_6_UNLCK', -1)
	STAT_SET_INT(mpx()..'CHAR_FM_CARMOD_7_UNLCK', -1)
	STAT_SET_INT(mpx()..'RACES_WON', 345+ rn())
	STAT_SET_INT(mpx()..'NUMBER_SLIPSTREAMS_IN_RACE', 213+ rn())
	STAT_SET_INT(mpx()..'NUMBER_TURBO_STARTS_IN_RACE', 200+ rn())
	STAT_SET_INT(mpx()..'MPPLY_TIMES_RACE_BEST_LAP', 300+ rn())
	STAT_SET_INT(mpx()..'AWD_FMRALLYWONDRIVE', 25)
	STAT_SET_INT(mpx()..'AWD_FMWINSEARACE', 144)
	STAT_SET_INT(mpx()..'AWD_FMWINAIRRACE', 76 + rn())
	STAT_SET_INT(mpx()..'AWD_FM_RACES_FASTEST_LAP', 201+ rn())
    STAT_SET_INT(mpx()..'CHAR_FM_VEHICLE_1_UNLCK', -1)
    STAT_SET_INT(mpx()..'CHAR_FM_VEHICLE_2_UNLCK', -1)
    STAT_SET_INT(mpx()..'USJS_FOUND', 50)
    STAT_SET_INT(mpx()..'USJS_COMPLETED', 50)
    STAT_SET_INT(mpx().."AWD_WIN_CAPTURES", 50)
			
	  STAT_SET_INT(mpx().."AWD_DROPOFF_CAP_PACKAGES", 100)
	  STAT_SET_INT(mpx().."AWD_KILL_CARRIER_CAPTURE", 100)
	  STAT_SET_INT(mpx().."AWD_FINISH_HEISTS", 50)
	  STAT_SET_INT(mpx().."AWD_FINISH_HEIST_SETUP_JOB", 50)
	  STAT_SET_INT(mpx().."AWD_NIGHTVISION_KILLS", 100)
	  STAT_SET_INT(mpx().."AWD_WIN_LAST_TEAM_STANDINGS", 50)
	  STAT_SET_INT(mpx().."AWD_ONLY_PLAYER_ALIVE_LTS", 50)
	  STAT_SET_INT(mpx().."AWD_TAXIDRIVER", 100)
		
	for i = 1, 20 do
		STAT_SET_INT(mpx().. "MPPLY_XMASLIVERIES" .. (i + 100), 1)
		STAT_SET_INT("MPPLY_XMASLIVERIES" .. (i + 100), 1)
	end
end


function UnlockBennyVehicleOptions()
	local flowCSAbilities = {"LOW_FLOW_CS_DRV_SEEN", "LOW_FLOW_CS_TRA_SEEN", "LOW_FLOW_CS_FUN_SEEN",
                         "LOW_FLOW_CS_PHO_SEEN", "LOW_FLOW_CS_FIN_SEEN", "LOW_BEN_INTRO_CS_SEEN"}

	for _, ability in ipairs(flowCSAbilities) do
	  STAT_SET_BOOL(mpx() .. ability, true)
	end
end
	
local function unlockAllTattoos()
    STAT_SET_INT(mpx() .. "TATTOO_FM_CURRENT_32", -1)
    for i = 0, 100 do
        STAT_SET_INT(mpx() .. "TATTOO_FM_UNLOCKS_" .. i, -1)
    end
end

		
menu.my_root():toggle("UNLOCK ALL!! (well.. allot not all!)", {}, "", function(on)
    if on then
	 STAT_SET_INT("MPPLY_CREW_NO_HEISTS_0", 2)
    STAT_SET_INT("MPPLY_CREW_NO_HEISTS_1", 5)
    STAT_SET_INT("MPPLY_CREW_NO_HEISTS_2", 5)
    STAT_SET_INT("MPPLY_CREW_NO_HEISTS_3", 5)
    STAT_SET_INT("MPPLY_CREW_NO_HEISTS_4", 5)
    STAT_SET_INT("MPPLY_GANGOPS_LOYALTY2", -1)
    STAT_SET_INT("MPPLY_GANGOPS_LOYALTY3", -1)
    STAT_SET_INT("MPPLY_GANGOPS_CRIMMASMD2", -1)
    STAT_SET_INT("MPPLY_GANGOPS_CRIMMASMD3", -1)
    STAT_SET_INT("MPPLY_GANGOPS_SUPPORT", -1)
    STAT_SET_INT("MPPLY_GANGOPS_ALLINORDER", -1)
    STAT_SET_INT("MPPLY_GANGOPS_LOYALTY", -1)
    STAT_SET_INT("MPPLY_GANGOPS_CRIMMASMD", -1)
    STAT_SET_INT("MPPLY_XMASLIVERIES0", -1)
    STAT_SET_INT("MPPLY_XMASLIVERIES1", -1)
    STAT_SET_INT("MPPLY_XMASLIVERIES2", -1)
    STAT_SET_INT("MPPLY_XMASLIVERIES3", -1)
    STAT_SET_INT("MPPLY_XMASLIVERIES4", -1)
    STAT_SET_INT("MPPLY_XMASLIVERIES5", -1)
    STAT_SET_INT("MPPLY_XMASLIVERIES6", -1)
    STAT_SET_INT("MPPLY_XMASLIVERIES7", -1)
    STAT_SET_INT("MPPLY_XMASLIVERIES8", -1)
    STAT_SET_INT("MPPLY_XMASLIVERIES9", -1)
    STAT_SET_INT("MPPLY_XMASLIVERIES10", -1)
    STAT_SET_INT("MPPLY_XMASLIVERIES11", -1)
    STAT_SET_INT("MPPLY_XMASLIVERIES12", -1)
    STAT_SET_INT("MPPLY_XMASLIVERIES13", -1)
    STAT_SET_INT("MPPLY_XMASLIVERIES14", -1)
    STAT_SET_INT("MPPLY_XMASLIVERIES15", -1)
    STAT_SET_INT("MPPLY_XMASLIVERIES16", -1)
    STAT_SET_INT("MPPLY_XMASLIVERIES17", -1)
    STAT_SET_INT("MPPLY_XMASLIVERIES18", -1)
    STAT_SET_INT("MPPLY_XMASLIVERIES19", -1)
    STAT_SET_INT("MPPLY_XMASLIVERIES20", -1)
    STAT_SET_INT(mpx() .. "HOLDUPS_BITSET", -1)
    STAT_SET_INT(mpx() .. "CHAR_ABILITY_1_UNLCK", -1)
    STAT_SET_INT(mpx() .. "CHAR_ABILITY_2_UNLCK", -1)
    STAT_SET_INT(mpx() .. "CHAR_ABILITY_3_UNLCK", -1)
    STAT_SET_INT(mpx() .. "CHAR_WEAP_UNLOCKED", -1)
    STAT_SET_INT(mpx() .. "CHAR_WEAP_UNLOCKED2", -1)
    STAT_SET_INT(mpx() .. "CHAR_WEAP_ADDON_1_UNLCK", -1)
    STAT_SET_INT(mpx() .. "CHAR_WEAP_ADDON_2_UNLCK", -1)
    STAT_SET_INT(mpx() .. "CHAR_WEAP_ADDON_3_UNLCK", -1)
    STAT_SET_INT(mpx() .. "CHAR_WEAP_ADDON_4_UNLCK", -1)
    STAT_SET_INT(mpx() .. "CHAR_FM_WEAP_UNLOCKED", -1)
    STAT_SET_INT(mpx() .. "CHAR_FM_WEAP_UNLOCKED2", -1)
    STAT_SET_INT(mpx() .. "CHAR_FM_WEAP_UNLOCKED3", -1)
    STAT_SET_INT(mpx() .. "CHAR_FM_WEAP_UNLOCKED4", -1)
    STAT_SET_INT(mpx() .. "CHAR_FM_WEAP_UNLOCKED5", -1)
    STAT_SET_INT(mpx() .. "CHAR_FM_WEAP_ADDON_1_UNLCK", -1)
    STAT_SET_INT(mpx() .. "CHAR_FM_WEAP_ADDON_2_UNLCK", -1)
    STAT_SET_INT(mpx() .. "CHAR_FM_WEAP_ADDON_3_UNLCK", -1)
    STAT_SET_INT(mpx() .. "CHAR_FM_WEAP_ADDON_4_UNLCK", -1)
    STAT_SET_INT(mpx() .. "CHAR_FM_WEAP_ADDON_5_UNLCK", -1)
    STAT_SET_INT(mpx() .. "CHAR_FM_WEAP_ADDON_6_UNLCK", -1)
    STAT_SET_INT(mpx() .. "CHAR_FM_WEAP_ADDON_7_UNLCK", -1)
    STAT_SET_INT(mpx() .. "CHAR_FM_WEAP_ADDON_8_UNLCK", -1)
    STAT_SET_INT(mpx() .. "CHAR_FM_WEAP_ADDON_9_UNLCK", -1)
    STAT_SET_INT(mpx() .. "CHAR_FM_WEAP_ADDON_10_UNLCK", -1)
    STAT_SET_INT(mpx() .. "CHAR_FM_WEAP_ADDON_11_UNLCK", -1)
    STAT_SET_INT(mpx() .. "CHAR_FM_WEAP_ADDON_12_UNLCK", -1)
    STAT_SET_INT(mpx() .. "CHAR_FM_WEAP_ADDON_13_UNLCK", -1)
    STAT_SET_INT(mpx() .. "CHAR_FM_WEAP_ADDON_14_UNLCK", -1)
    STAT_SET_INT(mpx() .. "CHAR_FM_WEAP_ADDON_15_UNLCK", -1)
    STAT_SET_INT(mpx() .. "CHAR_FM_WEAP_ADDON_16_UNLCK", -1)
    STAT_SET_INT(mpx() .. "CHAR_FM_WEAP_ADDON_17_UNLCK", -1)
    STAT_SET_INT(mpx() .. "CHAR_FM_WEAP_ADDON_18_UNLCK", -1)
    STAT_SET_INT(mpx() .. "CHAR_FM_WEAP_ADDON_19_UNLCK", -1)
    STAT_SET_INT(mpx() .. "CHAR_FM_WEAP_ADDON_20_UNLCK", -1)
    STAT_SET_INT(mpx() .. "CHAR_FM_HAIRCUT_1_UNLCK", -1)
    STAT_SET_INT(mpx() .. "CHAR_HAIR_UNLCK1", -1)
    STAT_SET_INT(mpx() .. "CHAR_HAIR_UNLCK2", -1)
    STAT_SET_INT(mpx() .. "CHAR_HAIR_UNLCK3", -1)
    STAT_SET_INT(mpx() .. "CHAR_HAIR_UNLCK4", -1)
    STAT_SET_INT(mpx() .. "CHAR_HAIR_UNLCK5", -1)
    STAT_SET_INT(mpx() .. "CHAR_HAIR_UNLCK6", -1)
    STAT_SET_INT(mpx() .. "CHAR_HAIR_UNLCK7", -1)
    STAT_SET_INT(mpx() .. "CHAR_HAIR_UNLCK8", -1)
    STAT_SET_INT(mpx() .. "CHAR_HAIR_UNLCK9", -1)
    STAT_SET_INT(mpx() .. "CHAR_HAIR_UNLCK10", -1)
    STAT_SET_INT(mpx() .. "CHAR_HAIR_UNLCK11", -1)
    STAT_SET_INT(mpx() .. "CHAR_HAIR_UNLCK12", -1)
    STAT_SET_INT(mpx() .. "CHAR_HAIR_UNLCK13", -1)
    STAT_SET_INT(mpx() .. "CHAR_HAIR_UNLCK14", -1)
    STAT_SET_INT(mpx() .. "CHAR_HAIR_UNLCK15",7)
		UnlockEngineUpgrades()
		unlockFastRunReload()
		UnlockALLparachutes()
		CompleteDailyObjectives()
		SpecialTats()
		unlockAllTattoos()
		UnlockBennyVehicleOptions()
		UnlockVehicleOptions()
		UnlockALL()
		SpecialTats()
		STAT_SET_INT(mpx() .. "ALLOW_GENDER_CHANGE", 52)
	end
end)

























RPtoRank = {
	0,
	800,
	2100,
	3800,
	6100,
	9500,
	12500,
	16000,
	19800,
	24000,
	28500,
	33400,
	38700,
	44200,
	50200,
	56400,
	63000,
	69900,
	77100,
	84700,
	92500,
	100700,
	109200,
	118000,
	127100,
	136500,
	146200,
	156200,
	166500,
	177100,
	188000,
	199200,
	210700,
	222400,
	234500,
	246800,
	259400,
	272300,
	285500,
	299000,
	312700,
	326800,
	341000,
	355600,
	370500,
	385600,
	401000,
	416600,
	432600,
	448800,
	465200,
	482000,
	499000,
	516300,
	533800,
	551600,
	569600,
	588000,
	606500,
	625400,
	644500,
	663800,
	683400,
	703300,
	723400,
	743800,
	764500,
	785400,
	806500,
	827900,
	849600,
	871500,
	893600,
	916000,
	938700,
	961600,
	984700,
	1008100,
	1031800,
	1055700,
	1079800,
	1104200,
	1128800,
	1153700,
	1178800,
	1204200,
	1229800,
	1255600,
	1281700,
	1308100,
	1334600,
	1361400,
	1388500,
	1415800,
	1443300,
}



local function calculaterp(value)
    if value >= 1 and value <= 94 then
        return RPtoRank[value] or 0
    else
        local num = value - 99
        local num2 = (num * (num + 1)) / 2
        return math.floor(1555800 + (num * 28500) + (num2 * 50))
    end
end

	
local selected_lvl = 158
function sellx()
	return selected_lvl
end
local maxOption = 8000
local function generateMenuItems()
    local items = {}
    for i = 1, maxOption do
        items[i] = {"Level " .. i}
    end
    return items
end
local menuItems = generateMenuItems()
    menu.my_root():list_select("Select your new Level", {}, "", menuItems, selected_lvl, function(value)
    selected_lvl = value
end)
menu.my_root():toggle("APPLY LEVEL (150+ to unlock all lvl req.)", {}, "", function(on)
    if on then
		local newRP = calculaterp(sellx())
		if util.get_char_slot() == 0 then
			STAT_SET_INT("MP0_CHAR_SET_RP_GIFT_ADMIN", newRP)
		else
			STAT_SET_INT("MP1_CHAR_SET_RP_GIFT_ADMIN", newRP)
		end
		  util.toast("Now join a new session!\nYour new level (".. sellx() ..") will be set!")
		  util.yield(1000)
		  util.toast("Now join a new session!\nYour new level (".. sellx() ..") will be set!")
		  util.yield(1000)
		  util.toast("Now join a new session!\nYour new level (".. sellx() ..") will be set!")
		  util.yield(1000)
		  util.toast("Now join a new session!\nYour new level (".. sellx() ..") will be set!")
		 util.yield(1000)
		  util.toast("Now join a new session!\nYour new level (".. sellx() ..") will be set!")
		 util.yield(1000)
		  util.toast("Now join a new session!\nYour new level (".. sellx() ..") will be set!")
		 util.yield(1000)
		  util.toast("Now join a new session!\nYour new level (".. sellx() ..") will be set!")
		util.yield(1000)
		  util.toast("Now join a new session!\nYour new level (".. sellx() ..") will be set!")
		util.yield(1000)
		  util.toast("Now join a new session!\nYour new level (".. sellx() ..") will be set!")
		util.yield(1000)
		  util.toast("Now join a new session!\nYour new level (".. sellx() ..") will be set!")
		util.yield(1000)
		  util.toast("Now join a new session!\nYour new level (".. sellx() ..") will be set!")
		util.yield(1000)
		  util.toast("Now join a new session!\nYour new level (".. sellx() ..") will be set!")
		util.yield(1000)
		  util.toast("Now join a new session!\nYour new level (".. sellx() ..") will be set!")
		util.yield(1000)
		  util.toast("Now join a new session!\nYour new level (".. sellx() ..") will be set!")
	end
	
end)



